import type { AIMeta } from '@/lib/data'

export type AITagResult = {
  sourceFileId: string
  characters: string[]
  scene?: string
  location?: string
  typeTag?: string
  confidence: number
  keywords: string[]
  analyzedAt: string
  status: 'processing' | 'complete'
}

/**
 * Mock AI analysis results for files in managed zones across all 5 departments.
 * Keyed by workspace file ID (from workspace-data.ts).
 */
const MOCK_AI_TAGS: Record<string, AITagResult> = {
  // Art — Concept Art (managed zone)
  'ws-art-concept-1': {
    sourceFileId: 'ws-art-concept-1',
    characters: ['Eleven'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    location: 'Hawkins Lab',
    typeTag: 'Concept Art',
    confidence: 0.94,
    keywords: ['hero pose', 'powers', 'telekinesis', 'nosebleed'],
    analyzedAt: '2026-02-13T10:30:00Z',
    status: 'complete',
  },
  'ws-art-concept-2': {
    sourceFileId: 'ws-art-concept-2',
    characters: ['Demogorgon'],
    location: 'The Upside Down',
    typeTag: 'Concept Art',
    confidence: 0.91,
    keywords: ['villain', 'creature', 'monster design', 'petals'],
    analyzedAt: '2026-02-12T14:15:00Z',
    status: 'complete',
  },
  // Art — Character Designs (managed zone)
  'ws-art-char-1': {
    sourceFileId: 'ws-art-char-1',
    characters: ['Eleven', 'Mike Wheeler'],
    typeTag: 'Character',
    confidence: 0.88,
    keywords: ['turnaround', 'character sheet', 'costume'],
    analyzedAt: '2026-02-11T09:00:00Z',
    status: 'complete',
  },
  'ws-art-char-2': {
    sourceFileId: 'ws-art-char-2',
    characters: ['Dustin Henderson', 'Jim Hopper', 'Joyce Byers'],
    typeTag: 'Character',
    confidence: 0.85,
    keywords: ['lineup', 'cast', 'supporting', 'group shot'],
    analyzedAt: '2026-02-10T16:45:00Z',
    status: 'complete',
  },

  // VFX — Shots (managed zone)
  'ws-vfx-010-010': {
    sourceFileId: 'ws-vfx-010-010',
    characters: ['Eleven'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    location: 'Hawkins Lab',
    typeTag: 'VFX Comp',
    confidence: 0.92,
    keywords: ['comp', 'final', 'powers effect', 'particle'],
    analyzedAt: '2026-02-14T08:00:00Z',
    status: 'complete',
  },
  'ws-vfx-010-020': {
    sourceFileId: 'ws-vfx-010-020',
    characters: ['Demogorgon'],
    scene: 'EXT. FOREST CHASE - DUSK',
    location: 'The Upside Down',
    typeTag: 'VFX Comp',
    confidence: 0.89,
    keywords: ['creature', 'portal', 'comp', 'atmosphere'],
    analyzedAt: '2026-02-13T11:30:00Z',
    status: 'complete',
  },
  'ws-vfx-010-030': {
    sourceFileId: 'ws-vfx-010-030',
    characters: [],
    scene: 'EXT. STARCOURT PARKING - NIGHT',
    location: 'Starcourt Mall',
    typeTag: 'VFX Comp',
    confidence: 0.78,
    keywords: ['environment', 'destruction', 'debris', 'fire'],
    analyzedAt: '2026-02-12T15:00:00Z',
    status: 'complete',
  },
  'ws-vfx-020-010': {
    sourceFileId: 'ws-vfx-020-010',
    characters: ['Mike Wheeler', 'Dustin Henderson'],
    scene: 'INT. WHEELER BASEMENT - DAY',
    typeTag: 'VFX Comp',
    confidence: 0.83,
    keywords: ['comp', 'walkie talkie', 'map', 'plan scene'],
    analyzedAt: '2026-02-13T09:45:00Z',
    status: 'complete',
  },
  'ws-vfx-020-020': {
    sourceFileId: 'ws-vfx-020-020',
    characters: ['Jim Hopper'],
    scene: 'EXT. GULAG YARD - DAY',
    typeTag: 'VFX Comp',
    confidence: 0.86,
    keywords: ['snow', 'guard tower', 'escape', 'comp'],
    analyzedAt: '2026-02-12T13:00:00Z',
    status: 'complete',
  },

  // Camera — Selects (managed zone)
  'ws-cam-sel-1': {
    sourceFileId: 'ws-cam-sel-1',
    characters: ['Eleven', 'Jim Hopper'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    location: 'Hawkins Lab',
    typeTag: 'Camera Select',
    confidence: 0.90,
    keywords: ['scene 12', 'take B', 'two-shot', 'emotional'],
    analyzedAt: '2026-02-13T07:30:00Z',
    status: 'complete',
  },
  'ws-cam-sel-2': {
    sourceFileId: 'ws-cam-sel-2',
    characters: ['Joyce Byers'],
    scene: 'EXT. FOREST CHASE - DUSK',
    location: 'Byers House',
    typeTag: 'Camera Select',
    confidence: 0.87,
    keywords: ['scene 15', 'take D', 'close-up', 'reaction'],
    analyzedAt: '2026-02-12T06:15:00Z',
    status: 'complete',
  },

  // Editorial — Cuts (managed zone)
  'ws-edit-cut-1': {
    sourceFileId: 'ws-edit-cut-1',
    characters: ['Eleven', 'Mike Wheeler', 'Jim Hopper'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    typeTag: 'Directors Cut',
    confidence: 0.95,
    keywords: ['EP301', 'directors cut', 'v4', 'full episode'],
    analyzedAt: '2026-02-14T12:00:00Z',
    status: 'complete',
  },
  'ws-edit-cut-2': {
    sourceFileId: 'ws-edit-cut-2',
    characters: ['Eleven', 'Dustin Henderson'],
    typeTag: 'Assembly',
    confidence: 0.82,
    keywords: ['EP301', 'assembly', 'v2', 'rough'],
    analyzedAt: '2026-02-12T10:00:00Z',
    status: 'complete',
  },
  'ws-edit-cut-3': {
    sourceFileId: 'ws-edit-cut-3',
    characters: ['Joyce Byers', 'Jim Hopper'],
    scene: 'EXT. GULAG YARD - DAY',
    typeTag: 'Rough Cut',
    confidence: 0.80,
    keywords: ['EP302', 'rough cut', 'v1', 'rescue arc'],
    analyzedAt: '2026-02-10T14:30:00Z',
    status: 'complete',
  },

  // Audio — Sound Effects (managed zone)
  'ws-audio-sfx-1': {
    sourceFileId: 'ws-audio-sfx-1',
    characters: [],
    location: 'The Upside Down',
    typeTag: 'SFX',
    confidence: 0.93,
    keywords: ['ambience', 'atmosphere', 'dark', 'reverb', 'otherworldly'],
    analyzedAt: '2026-02-12T11:00:00Z',
    status: 'complete',
  },
  'ws-audio-sfx-2': {
    sourceFileId: 'ws-audio-sfx-2',
    characters: ['Demogorgon'],
    typeTag: 'SFX',
    confidence: 0.96,
    keywords: ['creature', 'growl', 'roar', 'vocalization', 'monster'],
    analyzedAt: '2026-02-11T15:30:00Z',
    status: 'complete',
  },
  'ws-audio-sfx-3': {
    sourceFileId: 'ws-audio-sfx-3',
    characters: [],
    location: 'The Upside Down',
    typeTag: 'SFX',
    confidence: 0.88,
    keywords: ['portal', 'whoosh', 'transition', 'dimensional'],
    analyzedAt: '2026-02-10T09:00:00Z',
    status: 'complete',
  },

  // ── Art — Loose files ──
  'ws-art-loose-1': {
    sourceFileId: 'ws-art-loose-1',
    characters: [],
    typeTag: 'Notes',
    confidence: 0.72,
    keywords: ['notes', 'text', 'feedback', 'production'],
    analyzedAt: '2026-02-15T08:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-2': {
    sourceFileId: 'ws-art-loose-2',
    characters: ['Eleven'],
    typeTag: 'Concept Art',
    confidence: 0.79,
    keywords: ['feedback', 'revision', 'final', 'photoshop'],
    analyzedAt: '2026-02-14T09:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-3': {
    sourceFileId: 'ws-art-loose-3',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.65,
    keywords: ['screenshot', 'reference', 'capture'],
    analyzedAt: '2026-02-13T10:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-4': {
    sourceFileId: 'ws-art-loose-4',
    characters: [],
    location: 'Hawkins',
    typeTag: 'Mood Board',
    confidence: 0.81,
    keywords: ['mood board', 'tone', 'palette', 'inspiration'],
    analyzedAt: '2026-02-12T11:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-5': {
    sourceFileId: 'ws-art-loose-5',
    characters: [],
    typeTag: 'Color Test',
    confidence: 0.70,
    keywords: ['color', 'test', 'palette', 'swatch'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-6': {
    sourceFileId: 'ws-art-loose-6',
    characters: [],
    typeTag: 'Notes',
    confidence: 0.60,
    keywords: ['todo', 'cleanup', 'task list', 'markdown'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-7': {
    sourceFileId: 'ws-art-loose-7',
    characters: [],
    typeTag: 'WIP',
    confidence: 0.55,
    keywords: ['untitled', 'draft', 'work in progress'],
    analyzedAt: '2026-02-06T08:00:00Z',
    status: 'complete',
  },

  // Art — Storyboards
  'ws-art-sb-1': {
    sourceFileId: 'ws-art-sb-1',
    characters: ['Eleven', 'Mike Wheeler'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    typeTag: 'Storyboard',
    confidence: 0.90,
    keywords: ['storyboard', 'act 1', 'sequence 01', 'panels'],
    analyzedAt: '2026-02-12T09:00:00Z',
    status: 'complete',
  },
  'ws-art-sb-2': {
    sourceFileId: 'ws-art-sb-2',
    characters: ['Dustin Henderson'],
    scene: 'EXT. FOREST CHASE - DUSK',
    typeTag: 'Storyboard',
    confidence: 0.88,
    keywords: ['storyboard', 'act 1', 'sequence 02', 'panels'],
    analyzedAt: '2026-02-11T09:00:00Z',
    status: 'complete',
  },
  'ws-art-sb-3': {
    sourceFileId: 'ws-art-sb-3',
    characters: ['Jim Hopper', 'Joyce Byers'],
    scene: 'EXT. GULAG YARD - DAY',
    typeTag: 'Storyboard',
    confidence: 0.87,
    keywords: ['storyboard', 'act 2', 'sequence 01', 'panels'],
    analyzedAt: '2026-02-10T09:00:00Z',
    status: 'complete',
  },

  // Art — Environment Designs
  'ws-art-env-1': {
    sourceFileId: 'ws-art-env-1',
    characters: [],
    location: 'Hawkins',
    typeTag: 'Environment',
    confidence: 0.86,
    keywords: ['downtown', 'night', 'environment', 'cityscape'],
    analyzedAt: '2026-02-10T10:00:00Z',
    status: 'complete',
  },
  'ws-art-env-2': {
    sourceFileId: 'ws-art-env-2',
    characters: [],
    location: 'Hawkins Lab',
    typeTag: 'Environment',
    confidence: 0.84,
    keywords: ['warehouse', 'interior', 'environment', 'industrial'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },

  // Art — Props
  'ws-art-props-1': {
    sourceFileId: 'ws-art-props-1',
    characters: [],
    typeTag: 'Prop Design',
    confidence: 0.82,
    keywords: ['weapon', 'prop', 'hero', 'design', 'illustrator'],
    analyzedAt: '2026-02-09T11:00:00Z',
    status: 'complete',
  },
  'ws-art-props-2': {
    sourceFileId: 'ws-art-props-2',
    characters: [],
    typeTag: 'Prop Design',
    confidence: 0.80,
    keywords: ['vehicle', 'concept', 'prop', 'design'],
    analyzedAt: '2026-02-08T11:00:00Z',
    status: 'complete',
  },

  // Art — Color Scripts
  'ws-art-cs-1': {
    sourceFileId: 'ws-art-cs-1',
    characters: [],
    typeTag: 'Color Script',
    confidence: 0.83,
    keywords: ['color script', 'act 1', 'lighting', 'mood'],
    analyzedAt: '2026-02-08T12:00:00Z',
    status: 'complete',
  },
  'ws-art-cs-2': {
    sourceFileId: 'ws-art-cs-2',
    characters: [],
    typeTag: 'Color Script',
    confidence: 0.81,
    keywords: ['color script', 'act 2', 'lighting', 'mood'],
    analyzedAt: '2026-02-07T12:00:00Z',
    status: 'complete',
  },

  // Art — Reference
  'ws-art-ref-1': {
    sourceFileId: 'ws-art-ref-1',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.58,
    keywords: ['architecture', 'reference', 'archive', 'zip'],
    analyzedAt: '2026-02-07T13:00:00Z',
    status: 'complete',
  },
  'ws-art-ref-2': {
    sourceFileId: 'ws-art-ref-2',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.74,
    keywords: ['costume', 'research', 'reference', 'wardrobe'],
    analyzedAt: '2026-02-06T13:00:00Z',
    status: 'complete',
  },

  // ── VFX — Non-managed files ──
  'ws-vfx-3d-1': {
    sourceFileId: 'ws-vfx-3d-1',
    characters: [],
    typeTag: '3D Model',
    confidence: 0.85,
    keywords: ['vehicle', 'rigged', '3D', 'maya', 'hero'],
    analyzedAt: '2026-02-12T08:00:00Z',
    status: 'complete',
  },
  'ws-vfx-3d-2': {
    sourceFileId: 'ws-vfx-3d-2',
    characters: [],
    location: 'Starcourt Mall',
    typeTag: '3D Model',
    confidence: 0.82,
    keywords: ['building', 'destruction', 'simulation', 'houdini'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-vfx-tex-1': {
    sourceFileId: 'ws-vfx-tex-1',
    characters: [],
    typeTag: 'Texture',
    confidence: 0.90,
    keywords: ['concrete', 'damaged', '4K', 'texture', 'PBR'],
    analyzedAt: '2026-02-11T09:00:00Z',
    status: 'complete',
  },
  'ws-vfx-tex-2': {
    sourceFileId: 'ws-vfx-tex-2',
    characters: [],
    typeTag: 'Texture',
    confidence: 0.89,
    keywords: ['metal', 'scratched', '4K', 'texture', 'PBR'],
    analyzedAt: '2026-02-10T09:00:00Z',
    status: 'complete',
  },
  'ws-vfx-hdri-1': {
    sourceFileId: 'ws-vfx-hdri-1',
    characters: [],
    location: 'Hawkins',
    typeTag: 'HDRI',
    confidence: 0.91,
    keywords: ['downtown', 'night', '16K', 'HDRI', 'environment'],
    analyzedAt: '2026-02-10T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-hdri-2': {
    sourceFileId: 'ws-vfx-hdri-2',
    characters: [],
    typeTag: 'HDRI',
    confidence: 0.88,
    keywords: ['studio', 'soft light', '8K', 'HDRI', 'lighting'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-1': {
    sourceFileId: 'ws-vfx-elem-1',
    characters: [],
    typeTag: 'VFX Element',
    confidence: 0.87,
    keywords: ['dust', 'hits', 'practical', 'element', 'compositing'],
    analyzedAt: '2026-02-09T11:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-2': {
    sourceFileId: 'ws-vfx-elem-2',
    characters: [],
    typeTag: 'VFX Element',
    confidence: 0.85,
    keywords: ['sparks', '4K', 'ProRes', 'element', 'pyro'],
    analyzedAt: '2026-02-08T11:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-3': {
    sourceFileId: 'ws-vfx-elem-3',
    characters: [],
    typeTag: 'VFX Element',
    confidence: 0.83,
    keywords: ['smoke', 'plumes', 'element', 'atmosphere'],
    analyzedAt: '2026-02-07T11:00:00Z',
    status: 'complete',
  },
  'ws-vfx-script-1': {
    sourceFileId: 'ws-vfx-script-1',
    characters: [],
    typeTag: 'Script',
    confidence: 0.62,
    keywords: ['python', 'auto', 'comp', 'setup', 'pipeline'],
    analyzedAt: '2026-02-08T12:00:00Z',
    status: 'complete',
  },
  'ws-vfx-script-2': {
    sourceFileId: 'ws-vfx-script-2',
    characters: [],
    typeTag: 'Script',
    confidence: 0.60,
    keywords: ['python', 'render', 'submitter', 'pipeline'],
    analyzedAt: '2026-02-07T12:00:00Z',
    status: 'complete',
  },
  'ws-vfx-ref-1': {
    sourceFileId: 'ws-vfx-ref-1',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.76,
    keywords: ['explosion', 'reference', 'practical', 'pyro'],
    analyzedAt: '2026-02-07T13:00:00Z',
    status: 'complete',
  },
  'ws-vfx-ref-2': {
    sourceFileId: 'ws-vfx-ref-2',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.74,
    keywords: ['fluid', 'simulation', 'lookdev', 'reference'],
    analyzedAt: '2026-02-06T13:00:00Z',
    status: 'complete',
  },

  // ── Camera — Non-managed files ──
  'ws-cam-daily-1': {
    sourceFileId: 'ws-cam-daily-1',
    characters: ['Eleven', 'Jim Hopper'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    location: 'Hawkins Lab',
    typeTag: 'Daily',
    confidence: 0.88,
    keywords: ['A-cam', 'dailies', 'clip 001', 'scene coverage'],
    analyzedAt: '2026-02-14T06:00:00Z',
    status: 'complete',
  },
  'ws-cam-daily-2': {
    sourceFileId: 'ws-cam-daily-2',
    characters: ['Eleven'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    location: 'Hawkins Lab',
    typeTag: 'Daily',
    confidence: 0.86,
    keywords: ['A-cam', 'dailies', 'clip 002', 'coverage'],
    analyzedAt: '2026-02-14T06:15:00Z',
    status: 'complete',
  },
  'ws-cam-daily-3': {
    sourceFileId: 'ws-cam-daily-3',
    characters: ['Mike Wheeler', 'Dustin Henderson'],
    scene: 'INT. WHEELER BASEMENT - DAY',
    typeTag: 'Daily',
    confidence: 0.84,
    keywords: ['A-cam', 'dailies', 'clip 003', 'wide shot'],
    analyzedAt: '2026-02-14T06:30:00Z',
    status: 'complete',
  },
  'ws-cam-daily-4': {
    sourceFileId: 'ws-cam-daily-4',
    characters: ['Joyce Byers'],
    scene: 'INT. BYERS HOUSE - EVENING',
    location: 'Byers House',
    typeTag: 'Daily',
    confidence: 0.82,
    keywords: ['A-cam', 'dailies', 'clip 001', 'medium shot'],
    analyzedAt: '2026-02-13T06:00:00Z',
    status: 'complete',
  },
  'ws-cam-daily-5': {
    sourceFileId: 'ws-cam-daily-5',
    characters: ['Jim Hopper'],
    scene: 'EXT. GULAG YARD - DAY',
    typeTag: 'Daily',
    confidence: 0.80,
    keywords: ['A-cam', 'dailies', 'clip 002', 'tracking shot'],
    analyzedAt: '2026-02-13T06:15:00Z',
    status: 'complete',
  },
  'ws-cam-lut-1': {
    sourceFileId: 'ws-cam-lut-1',
    characters: [],
    typeTag: 'LUT',
    confidence: 0.70,
    keywords: ['LUT', 'ARRI', 'LogC4', 'Rec709', 'color transform'],
    analyzedAt: '2026-02-10T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-lut-2': {
    sourceFileId: 'ws-cam-lut-2',
    characters: [],
    typeTag: 'LUT',
    confidence: 0.68,
    keywords: ['LUT', 'show look', 'grade', 'color'],
    analyzedAt: '2026-02-09T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-lut-3': {
    sourceFileId: 'ws-cam-lut-3',
    characters: [],
    typeTag: 'LUT',
    confidence: 0.66,
    keywords: ['LUT', 'day exterior', 'grade', 'color'],
    analyzedAt: '2026-02-08T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-rpt-1': {
    sourceFileId: 'ws-cam-rpt-1',
    characters: [],
    typeTag: 'Report',
    confidence: 0.75,
    keywords: ['camera report', 'day 01', 'production', 'log'],
    analyzedAt: '2026-02-14T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-rpt-2': {
    sourceFileId: 'ws-cam-rpt-2',
    characters: [],
    typeTag: 'Report',
    confidence: 0.73,
    keywords: ['camera report', 'day 02', 'production', 'log'],
    analyzedAt: '2026-02-13T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-lens-1': {
    sourceFileId: 'ws-cam-lens-1',
    characters: [],
    typeTag: 'Lens Data',
    confidence: 0.65,
    keywords: ['lens', 'distortion', 'MasterPrime', '25mm', 'nuke'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },
  'ws-cam-lens-2': {
    sourceFileId: 'ws-cam-lens-2',
    characters: [],
    typeTag: 'Lens Data',
    confidence: 0.64,
    keywords: ['lens', 'distortion', 'MasterPrime', '50mm', 'nuke'],
    analyzedAt: '2026-02-08T08:00:00Z',
    status: 'complete',
  },
  'ws-cam-lens-3': {
    sourceFileId: 'ws-cam-lens-3',
    characters: [],
    typeTag: 'Lens Data',
    confidence: 0.62,
    keywords: ['lens', 'grid', 'charts', 'calibration'],
    analyzedAt: '2026-02-07T08:00:00Z',
    status: 'complete',
  },
  'ws-cam-spec-1': {
    sourceFileId: 'ws-cam-spec-1',
    characters: [],
    typeTag: 'Tech Spec',
    confidence: 0.68,
    keywords: ['ARRI', 'ALEXA 35', 'specifications', 'camera'],
    analyzedAt: '2026-02-08T09:00:00Z',
    status: 'complete',
  },
  'ws-cam-spec-2': {
    sourceFileId: 'ws-cam-spec-2',
    characters: [],
    typeTag: 'Tech Spec',
    confidence: 0.66,
    keywords: ['shooting format', 'guide', 'resolution', 'codec'],
    analyzedAt: '2026-02-07T09:00:00Z',
    status: 'complete',
  },

  // ── Editorial — Non-managed files ──
  'ws-edit-exp-1': {
    sourceFileId: 'ws-edit-exp-1',
    characters: ['Eleven', 'Mike Wheeler', 'Jim Hopper'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    typeTag: 'Export',
    confidence: 0.91,
    keywords: ['EP301', 'directors cut', 'ProRes', 'full export'],
    analyzedAt: '2026-02-13T08:00:00Z',
    status: 'complete',
  },
  'ws-edit-exp-2': {
    sourceFileId: 'ws-edit-exp-2',
    characters: ['Eleven', 'Mike Wheeler', 'Jim Hopper'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    typeTag: 'Export',
    confidence: 0.89,
    keywords: ['EP301', 'directors cut', 'H264', 'review copy'],
    analyzedAt: '2026-02-13T08:30:00Z',
    status: 'complete',
  },
  'ws-edit-vfx-1': {
    sourceFileId: 'ws-edit-vfx-1',
    characters: [],
    typeTag: 'VFX Pull',
    confidence: 0.78,
    keywords: ['EP301', 'VFX', 'pull list', 'spreadsheet'],
    analyzedAt: '2026-02-12T08:00:00Z',
    status: 'complete',
  },
  'ws-edit-vfx-2': {
    sourceFileId: 'ws-edit-vfx-2',
    characters: ['Demogorgon'],
    scene: 'EXT. FOREST CHASE - DUSK',
    typeTag: 'VFX Plate',
    confidence: 0.84,
    keywords: ['plate', 'SEQ010', 'SH020', 'clean plate'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-edit-script-1': {
    sourceFileId: 'ws-edit-script-1',
    characters: ['Eleven', 'Mike Wheeler', 'Dustin Henderson'],
    typeTag: 'Shooting Script',
    confidence: 0.92,
    keywords: ['EP301', 'shooting script', 'dialogue', 'production'],
    analyzedAt: '2026-02-10T08:00:00Z',
    status: 'complete',
  },
  'ws-edit-script-2': {
    sourceFileId: 'ws-edit-script-2',
    characters: ['Eleven', 'Mike Wheeler'],
    typeTag: 'Lined Script',
    confidence: 0.90,
    keywords: ['EP301', 'lined script', 'coverage', 'continuity'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },

  // ── Audio — Non-managed files ──
  'ws-audio-prod-1': {
    sourceFileId: 'ws-audio-prod-1',
    characters: [],
    typeTag: 'Sound Report',
    confidence: 0.73,
    keywords: ['sound report', 'day 01', 'production', 'log'],
    analyzedAt: '2026-02-14T08:00:00Z',
    status: 'complete',
  },
  'ws-audio-prod-2': {
    sourceFileId: 'ws-audio-prod-2',
    characters: ['Eleven', 'Jim Hopper'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    typeTag: 'Production Audio',
    confidence: 0.86,
    keywords: ['scene 12', 'take B', 'ISO', 'boom', 'dialogue'],
    analyzedAt: '2026-02-14T08:15:00Z',
    status: 'complete',
  },
  'ws-audio-prod-3': {
    sourceFileId: 'ws-audio-prod-3',
    characters: ['Eleven', 'Jim Hopper'],
    scene: 'INT. HAWKINS LAB - NIGHT',
    typeTag: 'Production Audio',
    confidence: 0.84,
    keywords: ['scene 12', 'take B', 'mix', 'stereo', 'dialogue'],
    analyzedAt: '2026-02-14T08:30:00Z',
    status: 'complete',
  },
  'ws-audio-music-1': {
    sourceFileId: 'ws-audio-music-1',
    characters: [],
    scene: 'INT. HAWKINS LAB - NIGHT',
    typeTag: 'Score',
    confidence: 0.88,
    keywords: ['EP301', 'score', 'cue 01', 'tension', 'synth'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-audio-music-2': {
    sourceFileId: 'ws-audio-music-2',
    characters: [],
    scene: 'EXT. FOREST CHASE - DUSK',
    typeTag: 'Score',
    confidence: 0.86,
    keywords: ['EP301', 'score', 'cue 02', 'chase', 'percussion'],
    analyzedAt: '2026-02-10T08:00:00Z',
    status: 'complete',
  },
  'ws-audio-music-3': {
    sourceFileId: 'ws-audio-music-3',
    characters: [],
    typeTag: 'Music',
    confidence: 0.75,
    keywords: ['80s', 'needle drop', 'options', 'licensed', 'archive'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },
  'ws-audio-mix-1': {
    sourceFileId: 'ws-audio-mix-1',
    characters: [],
    typeTag: 'Mix Session',
    confidence: 0.82,
    keywords: ['EP301', '5.1', 'mix', 'v2', 'Pro Tools'],
    analyzedAt: '2026-02-10T09:00:00Z',
    status: 'complete',
  },
  'ws-audio-mix-2': {
    sourceFileId: 'ws-audio-mix-2',
    characters: [],
    typeTag: 'Mix Session',
    confidence: 0.80,
    keywords: ['EP301', 'Atmos', 'mix', 'v1', 'Pro Tools', 'immersive'],
    analyzedAt: '2026-02-09T09:00:00Z',
    status: 'complete',
  },
}

/** Look up AI tags for a workspace file by its file node ID */
export function getAITagsForFile(fileId: string): AITagResult | undefined {
  return MOCK_AI_TAGS[fileId]
}

/** Convert an AITagResult to the AIMeta shape stored on Asset */
export function toAIMeta(tags: AITagResult): AIMeta {
  return {
    characters: tags.characters.length > 0 ? tags.characters : undefined,
    scene: tags.scene,
    location: tags.location,
    confidence: tags.confidence,
    keywords: tags.keywords,
  }
}
