import type { AIMeta, MediaAssetType } from '@/lib/data'

/**
 * AI-derived analysis of a workspace file. Carries narrative-layer references
 * (scene/character/location) AND Composite Concept references — productionShot,
 * cgShot, cgSequence, editSequence — so the file's relationships to first-class
 * ontology entities are a single source of truth. Plus mediaAssetType, the
 * work-product classification (editorial-cut, sound-mix, vfx-comp, etc.).
 */
export type AITagResult = {
  sourceFileId: string
  characters: string[]
  scene?: string
  location?: string
  /** Free-form display tag (e.g. "VFX Comp"). For controlled vocabulary, see mediaAssetType. */
  typeTag?: string
  /** Work-product classification (controlled vocab from the asset-taxonomy spec). */
  mediaAssetType?: MediaAssetType
  /** Composite Concept references — the parent entities this file belongs to. */
  productionShot?: string
  cgShot?: string
  cgSequence?: string
  editSequence?: string
  confidence: number
  keywords: string[]
  analyzedAt: string
  status: 'processing' | 'complete'
}

/**
 * Mock AI analysis results for files in managed zones across all 5 departments.
 * Keyed by workspace file ID (from workspace-data.ts).
 */
const MOCK_AI_TAGS: Record<string, AITagResult> = {
  // Art — Concept Art (managed zone)
  'ws-art-concept-1': {
    sourceFileId: 'ws-art-concept-1',
    characters: ['Marco Vitale'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Concept Art',
    confidence: 0.94,
    keywords: ['podium pose', 'powers', 'overtake', 'lockup'],
    analyzedAt: '2026-02-13T10:30:00Z',
    status: 'complete',
  },
  'ws-art-concept-2': {
    sourceFileId: 'ws-art-concept-2',
    characters: ['AR-24'],
    location: 'Pit Lane',
    typeTag: 'Concept Art',
    confidence: 0.91,
    keywords: ['villain', 'car', 'car design', 'aero'],
    analyzedAt: '2026-02-12T14:15:00Z',
    status: 'complete',
  },
  // Art — Character Designs (managed zone)
  'ws-art-char-1': {
    sourceFileId: 'ws-art-char-1',
    characters: ['Marco Vitale', 'James Ashworth'],
    typeTag: 'Character',
    confidence: 0.88,
    keywords: ['turnaround', 'character sheet', 'costume'],
    analyzedAt: '2026-02-11T09:00:00Z',
    status: 'complete',
  },
  'ws-art-char-2': {
    sourceFileId: 'ws-art-char-2',
    characters: ['Elena Richter', 'Viktor Dragan', 'Frank Castellano'],
    typeTag: 'Character',
    confidence: 0.85,
    keywords: ['lineup', 'cast', 'supporting', 'group shot'],
    analyzedAt: '2026-02-10T16:45:00Z',
    status: 'complete',
  },

  // VFX — Shots (managed zone)
  'ws-vfx-010-010': {
    sourceFileId: 'ws-vfx-010-010',
    characters: ['Marco Vitale'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'VFX Comp',
    mediaAssetType: 'vfx-comp',
    confidence: 0.92,
    keywords: ['comp', 'final', 'powers effect', 'particle'],
    analyzedAt: '2026-02-14T08:00:00Z',
    status: 'complete',
  },
  'ws-vfx-010-020': {
    sourceFileId: 'ws-vfx-010-020',
    characters: ['AR-24'],
    scene: 'EXT. CIRCUIT - LAP 52',
    location: 'Pit Lane',
    typeTag: 'VFX Comp',
    mediaAssetType: 'vfx-comp',
    cgShot: 'VFX_EP303_SC52_001',
    cgSequence: 'VFX_EP303_LAP52',
    confidence: 0.89,
    keywords: ['car', 'pit stop', 'comp', 'atmosphere'],
    analyzedAt: '2026-02-13T11:30:00Z',
    status: 'complete',
  },
  'ws-vfx-010-030': {
    sourceFileId: 'ws-vfx-010-030',
    characters: [],
    scene: 'EXT. PADDOCK - POST-RACE',
    location: 'Paddock Club',
    typeTag: 'VFX Comp',
    mediaAssetType: 'vfx-comp',
    confidence: 0.78,
    keywords: ['environment', 'destruction', 'debris', 'fire'],
    analyzedAt: '2026-02-12T15:00:00Z',
    status: 'complete',
  },
  'ws-vfx-020-010': {
    sourceFileId: 'ws-vfx-020-010',
    characters: ['James Ashworth', 'Elena Richter'],
    scene: 'INT. MERCEDES MOTORHOME - DEBRIEF',
    typeTag: 'VFX Comp',
    mediaAssetType: 'vfx-comp',
    confidence: 0.83,
    keywords: ['comp', 'team radio', 'map', 'plan scene'],
    analyzedAt: '2026-02-13T09:45:00Z',
    status: 'complete',
  },
  'ws-vfx-020-020': {
    sourceFileId: 'ws-vfx-020-020',
    characters: ['Viktor Dragan'],
    scene: 'EXT. GRID WALK - PRE-RACE',
    typeTag: 'VFX Comp',
    mediaAssetType: 'vfx-comp',
    confidence: 0.86,
    keywords: ['snow', 'guard tower', 'escape', 'comp'],
    analyzedAt: '2026-02-12T13:00:00Z',
    status: 'complete',
  },

  // Camera — Selects (managed zone)
  'ws-cam-sel-1': {
    sourceFileId: 'ws-cam-sel-1',
    characters: ['Marco Vitale', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Camera Select',
    mediaAssetType: 'camera-clip',
    productionShot: 'EP301-S05-T03A',
    confidence: 0.90,
    keywords: ['scene 12', 'take B', 'two-shot', 'emotional'],
    analyzedAt: '2026-02-13T07:30:00Z',
    status: 'complete',
  },
  'ws-cam-sel-2': {
    sourceFileId: 'ws-cam-sel-2',
    characters: ['Frank Castellano'],
    scene: 'EXT. CIRCUIT - LAP 52',
    location: 'FIA Stewards Office',
    typeTag: 'Camera Select',
    mediaAssetType: 'camera-clip',
    productionShot: 'EP303-S52-T07A',
    confidence: 0.87,
    keywords: ['scene 15', 'take D', 'close-up', 'reaction'],
    analyzedAt: '2026-02-12T06:15:00Z',
    status: 'complete',
  },

  // Editorial — Cuts (managed zone)
  'ws-edit-cut-1': {
    sourceFileId: 'ws-edit-cut-1',
    characters: ['Marco Vitale', 'James Ashworth', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Timeline',
    mediaAssetType: 'project-file',
    editSequence: 'cut-ep301-lc-1',
    confidence: 0.95,
    keywords: ['EP301', 'v4', 'full episode', 'premiere'],
    analyzedAt: '2026-02-14T12:00:00Z',
    status: 'complete',
  },
  'ws-edit-cut-2': {
    sourceFileId: 'ws-edit-cut-2',
    characters: ['Marco Vitale', 'Elena Richter'],
    typeTag: 'Timeline',
    confidence: 0.82,
    keywords: ['EP301', 'v2', 'premiere'],
    analyzedAt: '2026-02-12T10:00:00Z',
    status: 'complete',
  },
  'ws-edit-cut-3': {
    sourceFileId: 'ws-edit-cut-3',
    characters: ['Frank Castellano', 'Viktor Dragan'],
    scene: 'EXT. GRID WALK - PRE-RACE',
    typeTag: 'Timeline',
    confidence: 0.80,
    keywords: ['EP302', 'v1', 'premiere'],
    analyzedAt: '2026-02-10T14:30:00Z',
    status: 'complete',
  },

  // Editorial — Cut Constituents (managed zone)
  // Each file inside a cut folder gets editSequence (parent Edit Sequence
  // Concept) + mediaAssetType (work-product classification). This replaces the
  // earlier decorateCutConstituents pass — AI tags are now the single source.
  'ws-edit-lc1-video': {
    sourceFileId: 'ws-edit-lc1-video',
    characters: [], editSequence: 'cut-ep301-lc-1', mediaAssetType: 'editorial-cut',
    confidence: 1, keywords: ['picture lock', 'EP301', 'LC1'],
    analyzedAt: '2026-02-08T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc1-audio-stereo': {
    sourceFileId: 'ws-edit-lc1-audio-stereo',
    characters: [], editSequence: 'cut-ep301-lc-1', mediaAssetType: 'sound-mix', typeTag: 'Stereo',
    confidence: 1, keywords: ['mix', 'stereo'],
    analyzedAt: '2026-02-08T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc1-edl': {
    sourceFileId: 'ws-edit-lc1-edl',
    characters: [], editSequence: 'cut-ep301-lc-1', mediaAssetType: 'edl',
    confidence: 1, keywords: ['edit decision list'],
    analyzedAt: '2026-02-08T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc2-video': {
    sourceFileId: 'ws-edit-lc2-video',
    characters: [], editSequence: 'cut-ep301-lc-2', mediaAssetType: 'editorial-cut',
    confidence: 1, keywords: ['picture lock', 'EP301', 'LC2'],
    analyzedAt: '2026-02-13T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc2-audio-stereo': {
    sourceFileId: 'ws-edit-lc2-audio-stereo',
    characters: [], editSequence: 'cut-ep301-lc-2', mediaAssetType: 'sound-mix', typeTag: 'Stereo',
    confidence: 1, keywords: ['mix', 'stereo'],
    analyzedAt: '2026-02-13T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc2-audio-51': {
    sourceFileId: 'ws-edit-lc2-audio-51',
    characters: [], editSequence: 'cut-ep301-lc-2', mediaAssetType: 'sound-mix', typeTag: '5.1',
    confidence: 1, keywords: ['mix', 'surround'],
    analyzedAt: '2026-02-13T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc2-edl': {
    sourceFileId: 'ws-edit-lc2-edl',
    characters: [], editSequence: 'cut-ep301-lc-2', mediaAssetType: 'edl',
    confidence: 1, keywords: ['edit decision list'],
    analyzedAt: '2026-02-13T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc3-video': {
    sourceFileId: 'ws-edit-lc3-video',
    characters: [], editSequence: 'cut-ep301-lc-3', mediaAssetType: 'editorial-cut',
    confidence: 1, keywords: ['picture lock', 'EP301', 'LC3'],
    analyzedAt: '2026-02-18T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc3-audio-stereo': {
    sourceFileId: 'ws-edit-lc3-audio-stereo',
    characters: [], editSequence: 'cut-ep301-lc-3', mediaAssetType: 'sound-mix', typeTag: 'Stereo',
    confidence: 1, keywords: ['mix', 'stereo'],
    analyzedAt: '2026-02-18T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc3-audio-51': {
    sourceFileId: 'ws-edit-lc3-audio-51',
    characters: [], editSequence: 'cut-ep301-lc-3', mediaAssetType: 'sound-mix', typeTag: '5.1',
    confidence: 1, keywords: ['mix', 'surround'],
    analyzedAt: '2026-02-18T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc3-cc': {
    sourceFileId: 'ws-edit-lc3-cc',
    characters: [], editSequence: 'cut-ep301-lc-3', mediaAssetType: 'closed-captions',
    confidence: 1, keywords: ['captions', 'english', 'TTML'],
    analyzedAt: '2026-02-18T18:00:00Z', status: 'complete',
  },
  'ws-edit-lc3-edl': {
    sourceFileId: 'ws-edit-lc3-edl',
    characters: [], editSequence: 'cut-ep301-lc-3', mediaAssetType: 'edl',
    confidence: 1, keywords: ['edit decision list'],
    analyzedAt: '2026-02-18T18:00:00Z', status: 'complete',
  },
  'ws-edit-fc-video': {
    sourceFileId: 'ws-edit-fc-video',
    characters: [], editSequence: 'cut-ep301-fc', mediaAssetType: 'editorial-cut',
    confidence: 1, keywords: ['final cut', 'EP301'],
    analyzedAt: '2026-02-28T18:00:00Z', status: 'complete',
  },
  'ws-edit-fc-audio-stereo': {
    sourceFileId: 'ws-edit-fc-audio-stereo',
    characters: [], editSequence: 'cut-ep301-fc', mediaAssetType: 'sound-mix', typeTag: 'Stereo',
    confidence: 1, keywords: ['final mix', 'stereo'],
    analyzedAt: '2026-02-28T18:00:00Z', status: 'complete',
  },
  'ws-edit-fc-audio-51': {
    sourceFileId: 'ws-edit-fc-audio-51',
    characters: [], editSequence: 'cut-ep301-fc', mediaAssetType: 'sound-mix', typeTag: '5.1',
    confidence: 1, keywords: ['final mix', 'surround'],
    analyzedAt: '2026-02-28T18:00:00Z', status: 'complete',
  },
  'ws-edit-fc-audio-me': {
    sourceFileId: 'ws-edit-fc-audio-me',
    characters: [], editSequence: 'cut-ep301-fc', mediaAssetType: 'sound-mix', typeTag: 'M&E',
    confidence: 1, keywords: ['music and effects', 'localization'],
    analyzedAt: '2026-02-28T18:00:00Z', status: 'complete',
  },
  'ws-edit-fc-textless': {
    sourceFileId: 'ws-edit-fc-textless',
    characters: [], editSequence: 'cut-ep301-fc', mediaAssetType: 'textless-master',
    confidence: 1, keywords: ['textless', 'localization'],
    analyzedAt: '2026-02-28T18:00:00Z', status: 'complete',
  },
  'ws-edit-fc-edl': {
    sourceFileId: 'ws-edit-fc-edl',
    characters: [], editSequence: 'cut-ep301-fc', mediaAssetType: 'edl',
    confidence: 1, keywords: ['edit decision list', 'final'],
    analyzedAt: '2026-02-28T18:00:00Z', status: 'complete',
  },
  'ws-edit-emf-video': {
    sourceFileId: 'ws-edit-emf-video',
    characters: [], editSequence: 'cut-ep301-emf', mediaAssetType: 'editorial-cut',
    confidence: 1, keywords: ['delivery master', 'EP301', 'EMF'],
    analyzedAt: '2026-03-05T18:00:00Z', status: 'complete',
  },
  'ws-edit-emf-audio-stereo': {
    sourceFileId: 'ws-edit-emf-audio-stereo',
    characters: [], editSequence: 'cut-ep301-emf', mediaAssetType: 'sound-mix', typeTag: 'Stereo',
    confidence: 1, keywords: ['delivery mix', 'stereo'],
    analyzedAt: '2026-03-05T18:00:00Z', status: 'complete',
  },
  'ws-edit-emf-audio-51': {
    sourceFileId: 'ws-edit-emf-audio-51',
    characters: [], editSequence: 'cut-ep301-emf', mediaAssetType: 'sound-mix', typeTag: '5.1',
    confidence: 1, keywords: ['delivery mix', 'surround'],
    analyzedAt: '2026-03-05T18:00:00Z', status: 'complete',
  },
  'ws-edit-emf-audio-atmos': {
    sourceFileId: 'ws-edit-emf-audio-atmos',
    characters: [], editSequence: 'cut-ep301-emf', mediaAssetType: 'sound-mix', typeTag: 'Atmos',
    confidence: 1, keywords: ['delivery mix', 'immersive'],
    analyzedAt: '2026-03-05T18:00:00Z', status: 'complete',
  },
  'ws-edit-emf-audio-me': {
    sourceFileId: 'ws-edit-emf-audio-me',
    characters: [], editSequence: 'cut-ep301-emf', mediaAssetType: 'sound-mix', typeTag: 'M&E',
    confidence: 1, keywords: ['music and effects', 'localization'],
    analyzedAt: '2026-03-05T18:00:00Z', status: 'complete',
  },
  'ws-edit-emf-textless': {
    sourceFileId: 'ws-edit-emf-textless',
    characters: [], editSequence: 'cut-ep301-emf', mediaAssetType: 'textless-master',
    confidence: 1, keywords: ['textless', 'delivery'],
    analyzedAt: '2026-03-05T18:00:00Z', status: 'complete',
  },
  'ws-edit-emf-cc': {
    sourceFileId: 'ws-edit-emf-cc',
    characters: [], editSequence: 'cut-ep301-emf', mediaAssetType: 'closed-captions',
    confidence: 1, keywords: ['captions', 'english', 'TTML'],
    analyzedAt: '2026-03-05T18:00:00Z', status: 'complete',
  },
  'ws-edit-emf-qc': {
    sourceFileId: 'ws-edit-emf-qc',
    characters: [], editSequence: 'cut-ep301-emf', mediaAssetType: 'document',
    confidence: 1, keywords: ['QC report', 'delivery'],
    analyzedAt: '2026-03-05T18:00:00Z', status: 'complete',
  },
  'ws-edit-cut-rough2': {
    sourceFileId: 'ws-edit-cut-rough2',
    characters: [], editSequence: 'cut-ep302-lc-1', mediaAssetType: 'project-file',
    confidence: 1, keywords: ['EP302', 'timeline', 'v1'],
    analyzedAt: '2026-02-20T18:00:00Z', status: 'complete',
  },
  'ws-edit-ep302-lc1-video': {
    sourceFileId: 'ws-edit-ep302-lc1-video',
    characters: [], editSequence: 'cut-ep302-lc-1', mediaAssetType: 'editorial-cut',
    confidence: 1, keywords: ['picture lock', 'EP302', 'LC1'],
    analyzedAt: '2026-02-20T18:00:00Z', status: 'complete',
  },
  'ws-edit-ep302-lc1-audio': {
    sourceFileId: 'ws-edit-ep302-lc1-audio',
    characters: [], editSequence: 'cut-ep302-lc-1', mediaAssetType: 'sound-mix', typeTag: 'Stereo',
    confidence: 1, keywords: ['mix', 'stereo'],
    analyzedAt: '2026-02-20T18:00:00Z', status: 'complete',
  },
  'ws-edit-ep302-lc1-edl': {
    sourceFileId: 'ws-edit-ep302-lc1-edl',
    characters: [], editSequence: 'cut-ep302-lc-1', mediaAssetType: 'edl',
    confidence: 1, keywords: ['edit decision list'],
    analyzedAt: '2026-02-20T18:00:00Z', status: 'complete',
  },

  // Audio — Sound Effects (managed zone)
  'ws-audio-sfx-1': {
    sourceFileId: 'ws-audio-sfx-1',
    characters: [],
    location: 'Pit Lane',
    typeTag: 'SFX',
    confidence: 0.93,
    keywords: ['ambience', 'atmosphere', 'dark', 'reverb', 'mechanical'],
    analyzedAt: '2026-02-12T11:00:00Z',
    status: 'complete',
  },
  'ws-audio-sfx-2': {
    sourceFileId: 'ws-audio-sfx-2',
    characters: ['AR-24'],
    typeTag: 'SFX',
    confidence: 0.96,
    keywords: ['car', 'rev', 'acceleration', 'engine note', 'engine'],
    analyzedAt: '2026-02-11T15:30:00Z',
    status: 'complete',
  },
  'ws-audio-sfx-3': {
    sourceFileId: 'ws-audio-sfx-3',
    characters: [],
    location: 'Pit Lane',
    typeTag: 'SFX',
    confidence: 0.88,
    keywords: ['pit stop', 'whoosh', 'transition', 'dimensional'],
    analyzedAt: '2026-02-10T09:00:00Z',
    status: 'complete',
  },

  // ── Art — Loose files ──
  'ws-art-loose-1': {
    sourceFileId: 'ws-art-loose-1',
    characters: [],
    typeTag: 'Notes',
    confidence: 0.72,
    keywords: ['notes', 'text', 'feedback', 'production'],
    analyzedAt: '2026-02-15T08:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-2': {
    sourceFileId: 'ws-art-loose-2',
    characters: ['Marco Vitale'],
    typeTag: 'Concept Art',
    confidence: 0.79,
    keywords: ['feedback', 'revision', 'final', 'photoshop'],
    analyzedAt: '2026-02-14T09:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-3': {
    sourceFileId: 'ws-art-loose-3',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.65,
    keywords: ['screenshot', 'reference', 'capture'],
    analyzedAt: '2026-02-13T10:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-4': {
    sourceFileId: 'ws-art-loose-4',
    characters: [],
    location: 'Monaco',
    typeTag: 'Mood Board',
    confidence: 0.81,
    keywords: ['mood board', 'tone', 'palette', 'inspiration'],
    analyzedAt: '2026-02-12T11:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-5': {
    sourceFileId: 'ws-art-loose-5',
    characters: [],
    typeTag: 'Color Test',
    confidence: 0.70,
    keywords: ['color', 'test', 'palette', 'swatch'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-6': {
    sourceFileId: 'ws-art-loose-6',
    characters: [],
    typeTag: 'Notes',
    confidence: 0.60,
    keywords: ['todo', 'cleanup', 'task list', 'markdown'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },
  'ws-art-loose-7': {
    sourceFileId: 'ws-art-loose-7',
    characters: [],
    typeTag: 'WIP',
    confidence: 0.55,
    keywords: ['untitled', 'draft', 'work in progress'],
    analyzedAt: '2026-02-06T08:00:00Z',
    status: 'complete',
  },

  // Art — Storyboards
  'ws-art-sb-1': {
    sourceFileId: 'ws-art-sb-1',
    characters: ['Marco Vitale', 'James Ashworth'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Storyboard',
    confidence: 0.90,
    keywords: ['storyboard', 'act 1', 'sequence 01', 'panels'],
    analyzedAt: '2026-02-12T09:00:00Z',
    status: 'complete',
  },
  'ws-art-sb-2': {
    sourceFileId: 'ws-art-sb-2',
    characters: ['Elena Richter'],
    scene: 'EXT. CIRCUIT - LAP 52',
    typeTag: 'Storyboard',
    confidence: 0.88,
    keywords: ['storyboard', 'act 1', 'sequence 02', 'panels'],
    analyzedAt: '2026-02-11T09:00:00Z',
    status: 'complete',
  },
  'ws-art-sb-3': {
    sourceFileId: 'ws-art-sb-3',
    characters: ['Viktor Dragan', 'Frank Castellano'],
    scene: 'EXT. GRID WALK - PRE-RACE',
    typeTag: 'Storyboard',
    confidence: 0.87,
    keywords: ['storyboard', 'act 2', 'sequence 01', 'panels'],
    analyzedAt: '2026-02-10T09:00:00Z',
    status: 'complete',
  },

  // Art — Environment Designs
  'ws-art-env-1': {
    sourceFileId: 'ws-art-env-1',
    characters: [],
    location: 'Monaco',
    typeTag: 'Environment',
    confidence: 0.86,
    keywords: ['downtown', 'night', 'environment', 'cityscape'],
    analyzedAt: '2026-02-10T10:00:00Z',
    status: 'complete',
  },
  'ws-art-env-2': {
    sourceFileId: 'ws-art-env-2',
    characters: [],
    location: 'Apex Garage',
    typeTag: 'Environment',
    confidence: 0.84,
    keywords: ['warehouse', 'interior', 'environment', 'industrial'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },

  // Art — Props
  'ws-art-props-1': {
    sourceFileId: 'ws-art-props-1',
    characters: [],
    typeTag: 'Prop Design',
    confidence: 0.82,
    keywords: ['weapon', 'prop', 'hero', 'design', 'illustrator'],
    analyzedAt: '2026-02-09T11:00:00Z',
    status: 'complete',
  },
  'ws-art-props-2': {
    sourceFileId: 'ws-art-props-2',
    characters: [],
    typeTag: 'Prop Design',
    confidence: 0.80,
    keywords: ['vehicle', 'concept', 'prop', 'design'],
    analyzedAt: '2026-02-08T11:00:00Z',
    status: 'complete',
  },

  // Art — Color Scripts
  'ws-art-cs-1': {
    sourceFileId: 'ws-art-cs-1',
    characters: [],
    typeTag: 'Color Script',
    confidence: 0.83,
    keywords: ['color script', 'act 1', 'lighting', 'mood'],
    analyzedAt: '2026-02-08T12:00:00Z',
    status: 'complete',
  },
  'ws-art-cs-2': {
    sourceFileId: 'ws-art-cs-2',
    characters: [],
    typeTag: 'Color Script',
    confidence: 0.81,
    keywords: ['color script', 'act 2', 'lighting', 'mood'],
    analyzedAt: '2026-02-07T12:00:00Z',
    status: 'complete',
  },

  // Art — Reference
  'ws-art-ref-1': {
    sourceFileId: 'ws-art-ref-1',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.58,
    keywords: ['architecture', 'reference', 'archive', 'zip'],
    analyzedAt: '2026-02-07T13:00:00Z',
    status: 'complete',
  },
  'ws-art-ref-2': {
    sourceFileId: 'ws-art-ref-2',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.74,
    keywords: ['costume', 'research', 'reference', 'wardrobe'],
    analyzedAt: '2026-02-06T13:00:00Z',
    status: 'complete',
  },

  // ── VFX — Non-managed files ──
  'ws-vfx-3d-1': {
    sourceFileId: 'ws-vfx-3d-1',
    characters: [],
    typeTag: '3D Model',
    confidence: 0.85,
    keywords: ['vehicle', 'rigged', '3D', 'maya', 'hero'],
    analyzedAt: '2026-02-12T08:00:00Z',
    status: 'complete',
  },
  'ws-vfx-3d-2': {
    sourceFileId: 'ws-vfx-3d-2',
    characters: [],
    location: 'Paddock Club',
    typeTag: '3D Model',
    confidence: 0.82,
    keywords: ['building', 'destruction', 'simulation', 'houdini'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-vfx-tex-1': {
    sourceFileId: 'ws-vfx-tex-1',
    characters: [],
    typeTag: 'Texture',
    confidence: 0.90,
    keywords: ['concrete', 'damaged', '4K', 'texture', 'PBR'],
    analyzedAt: '2026-02-11T09:00:00Z',
    status: 'complete',
  },
  'ws-vfx-tex-2': {
    sourceFileId: 'ws-vfx-tex-2',
    characters: [],
    typeTag: 'Texture',
    confidence: 0.89,
    keywords: ['metal', 'scratched', '4K', 'texture', 'PBR'],
    analyzedAt: '2026-02-10T09:00:00Z',
    status: 'complete',
  },
  'ws-vfx-hdri-1': {
    sourceFileId: 'ws-vfx-hdri-1',
    characters: [],
    location: 'Monaco',
    typeTag: 'HDRI',
    confidence: 0.91,
    keywords: ['downtown', 'night', '16K', 'HDRI', 'environment'],
    analyzedAt: '2026-02-10T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-hdri-2': {
    sourceFileId: 'ws-vfx-hdri-2',
    characters: [],
    typeTag: 'HDRI',
    confidence: 0.88,
    keywords: ['studio', 'soft light', '8K', 'HDRI', 'lighting'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-1': {
    sourceFileId: 'ws-vfx-elem-1',
    characters: [],
    typeTag: 'VFX Element',
    confidence: 0.87,
    keywords: ['dust', 'hits', 'practical', 'element', 'compositing'],
    analyzedAt: '2026-02-09T11:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-2': {
    sourceFileId: 'ws-vfx-elem-2',
    characters: [],
    typeTag: 'VFX Element',
    confidence: 0.85,
    keywords: ['sparks', '4K', 'ProRes', 'element', 'pyro'],
    analyzedAt: '2026-02-08T11:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-3': {
    sourceFileId: 'ws-vfx-elem-3',
    characters: [],
    typeTag: 'VFX Element',
    confidence: 0.83,
    keywords: ['smoke', 'plumes', 'element', 'atmosphere'],
    analyzedAt: '2026-02-07T11:00:00Z',
    status: 'complete',
  },
  'ws-vfx-script-1': {
    sourceFileId: 'ws-vfx-script-1',
    characters: [],
    typeTag: 'Script',
    confidence: 0.62,
    keywords: ['python', 'auto', 'comp', 'setup', 'pipeline'],
    analyzedAt: '2026-02-08T12:00:00Z',
    status: 'complete',
  },
  'ws-vfx-script-2': {
    sourceFileId: 'ws-vfx-script-2',
    characters: [],
    typeTag: 'Script',
    confidence: 0.60,
    keywords: ['python', 'render', 'submitter', 'pipeline'],
    analyzedAt: '2026-02-07T12:00:00Z',
    status: 'complete',
  },
  'ws-vfx-ref-1': {
    sourceFileId: 'ws-vfx-ref-1',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.76,
    keywords: ['explosion', 'reference', 'practical', 'pyro'],
    analyzedAt: '2026-02-07T13:00:00Z',
    status: 'complete',
  },
  'ws-vfx-ref-2': {
    sourceFileId: 'ws-vfx-ref-2',
    characters: [],
    typeTag: 'Reference',
    confidence: 0.74,
    keywords: ['fluid', 'simulation', 'lookdev', 'reference'],
    analyzedAt: '2026-02-06T13:00:00Z',
    status: 'complete',
  },

  // ── Camera — Non-managed files ──
  'ws-cam-daily-1': {
    sourceFileId: 'ws-cam-daily-1',
    characters: ['Marco Vitale', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Daily',
    mediaAssetType: 'dailies-proxy',
    productionShot: 'EP301-S05-T03A',
    confidence: 0.88,
    keywords: ['A-cam', 'dailies', 'clip 001', 'scene coverage'],
    analyzedAt: '2026-02-14T06:00:00Z',
    status: 'complete',
  },
  'ws-cam-daily-2': {
    sourceFileId: 'ws-cam-daily-2',
    characters: ['Marco Vitale'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Daily',
    mediaAssetType: 'dailies-proxy',
    productionShot: 'EP301-S05-T03B',
    confidence: 0.86,
    keywords: ['A-cam', 'dailies', 'clip 002', 'coverage'],
    analyzedAt: '2026-02-14T06:15:00Z',
    status: 'complete',
  },
  'ws-cam-daily-3': {
    sourceFileId: 'ws-cam-daily-3',
    characters: ['James Ashworth', 'Elena Richter'],
    scene: 'INT. MERCEDES MOTORHOME - DEBRIEF',
    typeTag: 'Daily',
    confidence: 0.84,
    keywords: ['A-cam', 'dailies', 'clip 003', 'wide shot'],
    analyzedAt: '2026-02-14T06:30:00Z',
    status: 'complete',
  },
  'ws-cam-daily-4': {
    sourceFileId: 'ws-cam-daily-4',
    characters: ['Frank Castellano'],
    scene: 'INT. FIA STEWARDS OFFICE - EVENING',
    location: 'FIA Stewards Office',
    typeTag: 'Daily',
    confidence: 0.82,
    keywords: ['A-cam', 'dailies', 'clip 001', 'medium shot'],
    analyzedAt: '2026-02-13T06:00:00Z',
    status: 'complete',
  },
  'ws-cam-daily-5': {
    sourceFileId: 'ws-cam-daily-5',
    characters: ['Viktor Dragan'],
    scene: 'EXT. GRID WALK - PRE-RACE',
    typeTag: 'Daily',
    confidence: 0.80,
    keywords: ['A-cam', 'dailies', 'clip 002', 'tracking shot'],
    analyzedAt: '2026-02-13T06:15:00Z',
    status: 'complete',
  },
  'ws-cam-lut-1': {
    sourceFileId: 'ws-cam-lut-1',
    characters: [],
    typeTag: 'LUT',
    confidence: 0.70,
    keywords: ['LUT', 'ARRI', 'LogC4', 'Rec709', 'color transform'],
    analyzedAt: '2026-02-10T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-lut-2': {
    sourceFileId: 'ws-cam-lut-2',
    characters: [],
    typeTag: 'LUT',
    confidence: 0.68,
    keywords: ['LUT', 'show look', 'grade', 'color'],
    analyzedAt: '2026-02-09T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-lut-3': {
    sourceFileId: 'ws-cam-lut-3',
    characters: [],
    typeTag: 'LUT',
    confidence: 0.66,
    keywords: ['LUT', 'day exterior', 'grade', 'color'],
    analyzedAt: '2026-02-08T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-rpt-1': {
    sourceFileId: 'ws-cam-rpt-1',
    characters: [],
    typeTag: 'Report',
    confidence: 0.75,
    keywords: ['camera report', 'day 01', 'production', 'log'],
    analyzedAt: '2026-02-14T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-rpt-2': {
    sourceFileId: 'ws-cam-rpt-2',
    characters: [],
    typeTag: 'Report',
    confidence: 0.73,
    keywords: ['camera report', 'day 02', 'production', 'log'],
    analyzedAt: '2026-02-13T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-lens-1': {
    sourceFileId: 'ws-cam-lens-1',
    characters: [],
    typeTag: 'Lens Data',
    confidence: 0.65,
    keywords: ['lens', 'distortion', 'MasterPrime', '25mm', 'nuke'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },
  'ws-cam-lens-2': {
    sourceFileId: 'ws-cam-lens-2',
    characters: [],
    typeTag: 'Lens Data',
    confidence: 0.64,
    keywords: ['lens', 'distortion', 'MasterPrime', '50mm', 'nuke'],
    analyzedAt: '2026-02-08T08:00:00Z',
    status: 'complete',
  },
  'ws-cam-lens-3': {
    sourceFileId: 'ws-cam-lens-3',
    characters: [],
    typeTag: 'Lens Data',
    confidence: 0.62,
    keywords: ['lens', 'grid', 'charts', 'calibration'],
    analyzedAt: '2026-02-07T08:00:00Z',
    status: 'complete',
  },
  'ws-cam-spec-1': {
    sourceFileId: 'ws-cam-spec-1',
    characters: [],
    typeTag: 'Tech Spec',
    confidence: 0.68,
    keywords: ['ARRI', 'ALEXA 35', 'specifications', 'camera'],
    analyzedAt: '2026-02-08T09:00:00Z',
    status: 'complete',
  },
  'ws-cam-spec-2': {
    sourceFileId: 'ws-cam-spec-2',
    characters: [],
    typeTag: 'Tech Spec',
    confidence: 0.66,
    keywords: ['shooting format', 'guide', 'resolution', 'codec'],
    analyzedAt: '2026-02-07T09:00:00Z',
    status: 'complete',
  },

  // ── Editorial — Non-managed files ──
  'ws-edit-exp-1': {
    sourceFileId: 'ws-edit-exp-1',
    characters: ['Marco Vitale', 'James Ashworth', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Export',
    confidence: 0.91,
    keywords: ['EP301', 'ProRes', 'full export'],
    analyzedAt: '2026-02-13T08:00:00Z',
    status: 'complete',
  },
  'ws-edit-exp-2': {
    sourceFileId: 'ws-edit-exp-2',
    characters: ['Marco Vitale', 'James Ashworth', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Export',
    confidence: 0.89,
    keywords: ['EP301', 'H264', 'review copy'],
    analyzedAt: '2026-02-13T08:30:00Z',
    status: 'complete',
  },
  'ws-edit-vfx-1': {
    sourceFileId: 'ws-edit-vfx-1',
    characters: [],
    typeTag: 'VFX Pull',
    confidence: 0.78,
    keywords: ['EP301', 'VFX', 'pull list', 'spreadsheet'],
    analyzedAt: '2026-02-12T08:00:00Z',
    status: 'complete',
  },
  'ws-edit-vfx-2': {
    sourceFileId: 'ws-edit-vfx-2',
    characters: ['AR-24'],
    scene: 'EXT. CIRCUIT - LAP 52',
    typeTag: 'VFX Plate',
    mediaAssetType: 'vfx-plate',
    cgShot: 'VFX_EP303_SC52_001',
    cgSequence: 'VFX_EP303_LAP52',
    productionShot: 'EP303-S52-T07A',
    confidence: 0.84,
    keywords: ['plate', 'SEQ010', 'SH020', 'clean plate'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-edit-script-1': {
    sourceFileId: 'ws-edit-script-1',
    characters: ['Marco Vitale', 'James Ashworth', 'Elena Richter'],
    typeTag: 'Shooting Script',
    confidence: 0.92,
    keywords: ['EP301', 'shooting script', 'dialogue', 'production'],
    analyzedAt: '2026-02-10T08:00:00Z',
    status: 'complete',
  },
  'ws-edit-script-2': {
    sourceFileId: 'ws-edit-script-2',
    characters: ['Marco Vitale', 'James Ashworth'],
    typeTag: 'Lined Script',
    confidence: 0.90,
    keywords: ['EP301', 'lined script', 'coverage', 'continuity'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },

  // ── Audio — Non-managed files ──
  'ws-audio-prod-1': {
    sourceFileId: 'ws-audio-prod-1',
    characters: [],
    typeTag: 'Sound Report',
    confidence: 0.73,
    keywords: ['sound report', 'day 01', 'production', 'log'],
    analyzedAt: '2026-02-14T08:00:00Z',
    status: 'complete',
  },
  'ws-audio-prod-2': {
    sourceFileId: 'ws-audio-prod-2',
    characters: ['Marco Vitale', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Production Audio',
    confidence: 0.86,
    keywords: ['scene 12', 'take B', 'ISO', 'boom', 'dialogue'],
    analyzedAt: '2026-02-14T08:15:00Z',
    status: 'complete',
  },
  'ws-audio-prod-3': {
    sourceFileId: 'ws-audio-prod-3',
    characters: ['Marco Vitale', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Production Audio',
    confidence: 0.84,
    keywords: ['scene 12', 'take B', 'mix', 'stereo', 'dialogue'],
    analyzedAt: '2026-02-14T08:30:00Z',
    status: 'complete',
  },
  'ws-audio-music-1': {
    sourceFileId: 'ws-audio-music-1',
    characters: [],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Score',
    confidence: 0.88,
    keywords: ['EP301', 'score', 'cue 01', 'tension', 'synth'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-audio-music-2': {
    sourceFileId: 'ws-audio-music-2',
    characters: [],
    scene: 'EXT. CIRCUIT - LAP 52',
    typeTag: 'Score',
    confidence: 0.86,
    keywords: ['EP301', 'score', 'cue 02', 'chase', 'percussion'],
    analyzedAt: '2026-02-10T08:00:00Z',
    status: 'complete',
  },
  'ws-audio-music-3': {
    sourceFileId: 'ws-audio-music-3',
    characters: [],
    typeTag: 'Music',
    confidence: 0.75,
    keywords: ['80s', 'needle drop', 'options', 'licensed', 'archive'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },
  'ws-audio-mix-1': {
    sourceFileId: 'ws-audio-mix-1',
    characters: [],
    typeTag: 'Mix Session',
    confidence: 0.82,
    keywords: ['EP301', '5.1', 'mix', 'v2', 'Pro Tools'],
    analyzedAt: '2026-02-10T09:00:00Z',
    status: 'complete',
  },
  'ws-audio-mix-2': {
    sourceFileId: 'ws-audio-mix-2',
    characters: [],
    typeTag: 'Mix Session',
    confidence: 0.80,
    keywords: ['EP301', 'Atmos', 'mix', 'v1', 'Pro Tools', 'immersive'],
    analyzedAt: '2026-02-09T09:00:00Z',
    status: 'complete',
  },

  // ── Shared Folder: VFX → Editorial ──
  'shared-vfx2ed-1': {
    sourceFileId: 'shared-vfx2ed-1',
    characters: ['Marco Vitale'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'VFX Comp',
    confidence: 0.95,
    keywords: ['approved', 'comp', 'final', 'delivery', 'editorial'],
    analyzedAt: '2026-02-14T14:00:00Z',
    status: 'complete',
  },
  'shared-vfx2ed-2': {
    sourceFileId: 'shared-vfx2ed-2',
    characters: ['AR-24'],
    scene: 'EXT. CIRCUIT - LAP 52',
    location: 'Pit Lane',
    typeTag: 'VFX Comp',
    confidence: 0.92,
    keywords: ['approved', 'car', 'comp', 'delivery', 'editorial'],
    analyzedAt: '2026-02-13T14:00:00Z',
    status: 'complete',
  },
  'shared-vfx2ed-3': {
    sourceFileId: 'shared-vfx2ed-3',
    characters: ['James Ashworth', 'Elena Richter'],
    scene: 'INT. MERCEDES MOTORHOME - DEBRIEF',
    typeTag: 'VFX Comp',
    confidence: 0.88,
    keywords: ['approved', 'comp', 'delivery', 'editorial'],
    analyzedAt: '2026-02-12T14:00:00Z',
    status: 'complete',
  },

  // ── Shared Folder: Editorial → VFX ──
  'shared-ed2vfx-1': {
    sourceFileId: 'shared-ed2vfx-1',
    characters: ['AR-24'],
    scene: 'EXT. CIRCUIT - LAP 52',
    typeTag: 'VFX Plate',
    confidence: 0.90,
    keywords: ['plates', 'delivery', 'vfx', 'editorial cut'],
    analyzedAt: '2026-02-13T16:00:00Z',
    status: 'complete',
  },
  'shared-ed2vfx-2': {
    sourceFileId: 'shared-ed2vfx-2',
    characters: ['Marco Vitale', 'James Ashworth', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Reference Cut',
    confidence: 0.93,
    keywords: ['reference', 'cut', 'editorial'],
    analyzedAt: '2026-02-12T16:00:00Z',
    status: 'complete',
  },

  // ── Shared Folder: VFX → Vendor ──
  'shared-vfx2ven-1': {
    sourceFileId: 'shared-vfx2ven-1',
    characters: [],
    scene: 'EXT. PADDOCK - POST-RACE',
    location: 'Paddock Club',
    typeTag: 'VFX Plate',
    confidence: 0.85,
    keywords: ['plate', 'vendor', 'framestore', 'environment'],
    analyzedAt: '2026-02-12T18:00:00Z',
    status: 'complete',
  },
  'shared-vfx2ven-2': {
    sourceFileId: 'shared-vfx2ven-2',
    characters: ['Viktor Dragan'],
    scene: 'EXT. GRID WALK - PRE-RACE',
    typeTag: 'VFX Plate',
    confidence: 0.83,
    keywords: ['plate', 'vendor', 'framestore', 'grid walk'],
    analyzedAt: '2026-02-11T18:00:00Z',
    status: 'complete',
  },
  'shared-vfx2ven-3': {
    sourceFileId: 'shared-vfx2ven-3',
    characters: [],
    typeTag: 'Brief',
    confidence: 0.78,
    keywords: ['brief', 'vendor', 'framestore', 'EP301', 'scope'],
    analyzedAt: '2026-02-10T18:00:00Z',
    status: 'complete',
  },

  // ── Grounded API assets: Art Department ──
  'ws-art-concept-demogorgon': {
    sourceFileId: 'ws-art-concept-demogorgon',
    characters: ['AR-24'],
    location: 'Pit Lane',
    typeTag: 'Concept Art',
    confidence: 0.92,
    keywords: ['concept art', 'car', 'car design'],
    analyzedAt: '2026-02-11T10:00:00Z',
    status: 'complete',
  },
  'ws-art-concept-ud-env': {
    sourceFileId: 'ws-art-concept-ud-env',
    characters: [],
    location: 'Pit Lane',
    typeTag: 'Concept Art',
    confidence: 0.90,
    keywords: ['environment', 'concept art', 'dark'],
    analyzedAt: '2026-02-10T10:00:00Z',
    status: 'complete',
  },
  'ws-art-concept-creature': {
    sourceFileId: 'ws-art-concept-creature',
    characters: ['AR-24'],
    location: 'Pit Lane',
    typeTag: 'Concept Art',
    confidence: 0.91,
    keywords: ['car', 'design', 'engine'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },
  'ws-art-concept-lab': {
    sourceFileId: 'ws-art-concept-lab',
    characters: [],
    location: 'Apex Garage',
    typeTag: 'Concept Art',
    confidence: 0.88,
    keywords: ['interior', 'concept art', 'laboratory'],
    analyzedAt: '2026-02-08T10:00:00Z',
    status: 'complete',
  },
  'ws-art-sb-animatic': {
    sourceFileId: 'ws-art-sb-animatic',
    characters: ['Luca Ferreira'],
    location: 'Pit Lane',
    typeTag: 'Animatic',
    confidence: 0.86,
    keywords: ['animatic', 'season 3'],
    analyzedAt: '2026-02-09T09:00:00Z',
    status: 'complete',
  },
  'ws-art-sb-seq12': {
    sourceFileId: 'ws-art-sb-seq12',
    characters: ['Marco Vitale', 'James Ashworth'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Storyboard',
    confidence: 0.89,
    keywords: ['storyboard', 'sequence'],
    analyzedAt: '2026-02-08T09:00:00Z',
    status: 'complete',
  },
  'ws-art-sb-ep01': {
    sourceFileId: 'ws-art-sb-ep01',
    characters: ['Marco Vitale', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Storyboard',
    confidence: 0.90,
    keywords: ['storyboard', 'episode 1'],
    analyzedAt: '2026-02-07T09:00:00Z',
    status: 'complete',
  },
  'ws-art-sb-chase': {
    sourceFileId: 'ws-art-sb-chase',
    characters: ['Marco Vitale', 'AR-24'],
    scene: 'EXT. CIRCUIT - LAP 52',
    typeTag: 'Storyboard',
    confidence: 0.87,
    keywords: ['chase', 'storyboard', 'action'],
    analyzedAt: '2026-02-06T09:00:00Z',
    status: 'complete',
  },
  'ws-art-char-billy': {
    sourceFileId: 'ws-art-char-billy',
    characters: ['Luca Ferreira'],
    typeTag: 'Costume Design',
    confidence: 0.85,
    keywords: ['costume', 'design', 'race suit'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },
  'ws-art-char-hopper': {
    sourceFileId: 'ws-art-char-hopper',
    characters: ['Viktor Dragan'],
    typeTag: 'Costume Design',
    confidence: 0.87,
    keywords: ['team wear', 'costume', 'team principal'],
    analyzedAt: '2026-02-08T10:00:00Z',
    status: 'complete',
  },
  'ws-art-char-eleven': {
    sourceFileId: 'ws-art-char-eleven',
    characters: ['Marco Vitale'],
    typeTag: 'Costume Design',
    confidence: 0.86,
    keywords: ['race suit', 'costume', 'design'],
    analyzedAt: '2026-02-07T10:00:00Z',
    status: 'complete',
  },
  'ws-art-env-byers': {
    sourceFileId: 'ws-art-env-byers',
    characters: [],
    location: 'FIA Stewards Office',
    typeTag: 'Blueprint',
    confidence: 0.84,
    keywords: ['floor plan', 'blueprint', 'set design'],
    analyzedAt: '2026-02-08T11:00:00Z',
    status: 'complete',
  },
  'ws-art-env-starcourt': {
    sourceFileId: 'ws-art-env-starcourt',
    characters: [],
    location: 'Paddock Club',
    typeTag: 'Blueprint',
    confidence: 0.83,
    keywords: ['blueprint', 'mall', 'set design'],
    analyzedAt: '2026-02-07T11:00:00Z',
    status: 'complete',
  },

  // ── Grounded API assets: VFX Department ──
  'ws-vfx-3d-demogorgon': {
    sourceFileId: 'ws-vfx-3d-demogorgon',
    characters: ['AR-24'],
    location: 'Pit Lane',
    typeTag: 'VFX Preview',
    confidence: 0.91,
    keywords: ['rig', 'car', '3d'],
    analyzedAt: '2026-02-10T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-3d-demo-tex': {
    sourceFileId: 'ws-vfx-3d-demo-tex',
    characters: ['AR-24'],
    typeTag: 'Car FX',
    confidence: 0.89,
    keywords: ['texture', 'car', 'maps'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-3d-mindflayer': {
    sourceFileId: 'ws-vfx-3d-mindflayer',
    characters: ['AR-24'],
    location: 'Paddock Club',
    typeTag: 'VFX Preview',
    confidence: 0.88,
    keywords: ['mercedes w15', '3d', 'model'],
    analyzedAt: '2026-02-08T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-fog': {
    sourceFileId: 'ws-vfx-elem-fog',
    characters: [],
    location: 'Pit Lane',
    typeTag: 'VFX Preview',
    confidence: 0.87,
    keywords: ['fog', 'simulation', 'environment'],
    analyzedAt: '2026-02-06T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-preview': {
    sourceFileId: 'ws-vfx-elem-preview',
    characters: ['AR-24'],
    location: 'Pit Lane',
    scene: 'EXT. CIRCUIT - LAP 52',
    typeTag: 'VFX Preview',
    confidence: 0.90,
    keywords: ['vfx', 'pit stop', 'atmosphere'],
    analyzedAt: '2026-02-04T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-elem-notes': {
    sourceFileId: 'ws-vfx-elem-notes',
    characters: [],
    location: 'Pit Lane',
    typeTag: 'Virtual Art',
    confidence: 0.78,
    keywords: ['virtual art', 'notes', 'environment'],
    analyzedAt: '2026-02-03T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-comp-eleven': {
    sourceFileId: 'ws-vfx-comp-eleven',
    characters: ['Marco Vitale'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'VFX Preview',
    mediaAssetType: 'project-file',
    confidence: 0.92,
    keywords: ['powers', 'comp', 'vfx'],
    analyzedAt: '2026-02-11T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-comp-lab': {
    sourceFileId: 'ws-vfx-comp-lab',
    characters: [],
    scene: 'EXT. PADDOCK - POST-RACE',
    location: 'Apex Garage',
    typeTag: 'VFX Preview',
    mediaAssetType: 'project-file',
    confidence: 0.86,
    keywords: ['destruction', 'comp', 'explosion'],
    analyzedAt: '2026-02-10T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-matte-ud': {
    sourceFileId: 'ws-vfx-matte-ud',
    characters: [],
    location: 'Pit Lane',
    typeTag: 'Matte Painting',
    confidence: 0.85,
    keywords: ['matte painting', 'environment', 'pit lane'],
    analyzedAt: '2026-02-08T10:00:00Z',
    status: 'complete',
  },
  'ws-vfx-matte-skyline': {
    sourceFileId: 'ws-vfx-matte-skyline',
    characters: [],
    location: 'Monaco',
    typeTag: 'Matte Painting',
    confidence: 0.83,
    keywords: ['matte painting', 'skyline', 'monaco'],
    analyzedAt: '2026-02-07T10:00:00Z',
    status: 'complete',
  },

  // ── Grounded API assets: Camera Department ──
  'ws-cam-sel-billy': {
    sourceFileId: 'ws-cam-sel-billy',
    characters: ['Luca Ferreira'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Zandvoort Circuit',
    typeTag: 'Camera Select',
    confidence: 0.93,
    keywords: ['close-up', 'confrontation'],
    analyzedAt: '2026-02-11T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-sel-eleven': {
    sourceFileId: 'ws-cam-sel-eleven',
    characters: ['Marco Vitale'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Camera Select',
    confidence: 0.91,
    keywords: ['powers', 'awakening', 'overtake'],
    analyzedAt: '2026-02-10T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-sel-portal': {
    sourceFileId: 'ws-cam-sel-portal',
    characters: ['Marco Vitale'],
    scene: 'EXT. CIRCUIT - LAP 52',
    location: 'Pit Lane',
    typeTag: 'Camera Select',
    confidence: 0.90,
    keywords: ['pit stop', 'opening', 'dimensional'],
    analyzedAt: '2026-02-09T07:00:00Z',
    status: 'complete',
  },
  'ws-cam-broll-town': {
    sourceFileId: 'ws-cam-broll-town',
    characters: [],
    location: 'Zandvoort Circuit',
    typeTag: 'B-Roll',
    confidence: 0.82,
    keywords: ['town square', 'b-roll', 'establishing'],
    analyzedAt: '2026-02-11T08:00:00Z',
    status: 'complete',
  },
  'ws-cam-steadicam-chase': {
    sourceFileId: 'ws-cam-steadicam-chase',
    characters: ['Marco Vitale', 'AR-24'],
    scene: 'EXT. CIRCUIT - LAP 52',
    typeTag: 'Steadicam',
    confidence: 0.88,
    keywords: ['chase', 'steadicam', 'action'],
    analyzedAt: '2026-02-09T08:00:00Z',
    status: 'complete',
  },
  'ws-cam-rpt-shotlist': {
    sourceFileId: 'ws-cam-rpt-shotlist',
    characters: [],
    scene: 'EXT. GRID WALK - PRE-RACE',
    typeTag: 'Shot List',
    confidence: 0.80,
    keywords: ['shot list', 'master'],
    analyzedAt: '2026-02-12T08:00:00Z',
    status: 'complete',
  },

  // ── Grounded API assets: Editorial Department ──
  'ws-edit-cut-locked': {
    sourceFileId: 'ws-edit-cut-locked',
    characters: ['Luca Ferreira', 'Marco Vitale'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Locked Cut',
    confidence: 0.94,
    keywords: ['locked cut', 'episode 7'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },
  'ws-edit-cut-rough1': {
    sourceFileId: 'ws-edit-cut-rough1',
    characters: ['Marco Vitale', 'James Ashworth', 'Viktor Dragan'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    location: 'Apex Garage',
    typeTag: 'Rough Cut',
    confidence: 0.91,
    keywords: ['rough cut', 'episode 1'],
    analyzedAt: '2026-02-08T10:00:00Z',
    status: 'complete',
  },
  'ws-edit-cut-assembly': {
    sourceFileId: 'ws-edit-cut-assembly',
    characters: ['Marco Vitale', 'Elena Richter'],
    scene: 'INT. MERCEDES MOTORHOME - DEBRIEF',
    typeTag: 'Assembly',
    confidence: 0.85,
    keywords: ['assembly', 'episode 1'],
    analyzedAt: '2026-02-06T10:00:00Z',
    status: 'complete',
  },
  'ws-edit-script-ep07': {
    sourceFileId: 'ws-edit-script-ep07',
    characters: ['Luca Ferreira', 'Marco Vitale'],
    scene: 'INT. APEX GARAGE - RACE DAY',
    typeTag: 'Script',
    confidence: 0.93,
    keywords: ['script', 'final', 'episode 7'],
    analyzedAt: '2026-02-08T10:00:00Z',
    status: 'complete',
  },

  // ── Grounded API assets: Audio Department ──
  'ws-audio-sfx-growl': {
    sourceFileId: 'ws-audio-sfx-growl',
    characters: ['AR-24'],
    typeTag: 'SFX',
    confidence: 0.95,
    keywords: ['rev', 'car', 'sfx'],
    analyzedAt: '2026-02-09T10:00:00Z',
    status: 'complete',
  },
  'ws-audio-sfx-powers': {
    sourceFileId: 'ws-audio-sfx-powers',
    characters: ['Marco Vitale'],
    typeTag: 'SFX',
    confidence: 0.88,
    keywords: ['powers', 'overtake', 'sfx'],
    analyzedAt: '2026-02-07T10:00:00Z',
    status: 'complete',
  },
  'ws-audio-sfx-ambience': {
    sourceFileId: 'ws-audio-sfx-ambience',
    characters: [],
    location: 'Pit Lane',
    typeTag: 'Ambient',
    confidence: 0.90,
    keywords: ['ambience', 'atmosphere', 'dark'],
    analyzedAt: '2026-02-06T10:00:00Z',
    status: 'complete',
  },
  'ws-audio-adr-eleven': {
    sourceFileId: 'ws-audio-adr-eleven',
    characters: ['Marco Vitale'],
    typeTag: 'ADR',
    confidence: 0.87,
    keywords: ['adr', 'dialogue', 'voice'],
    analyzedAt: '2026-02-04T10:00:00Z',
    status: 'complete',
  },

  // ══════════════════════════════════════════════════════════════════
  // Mid-production bulk assets — realistic tag volume for Apex S1
  // Ep 1-3 in post, Ep 4 shooting, Ep 5-8 in pre-prod
  // ══════════════════════════════════════════════════════════════════

  // ── Camera dailies & selects: Luca Ferreira coverage ──
  'gen-cam-ferreira-01': { sourceFileId: 'gen-cam-ferreira-01', characters: ['Luca Ferreira'], scene: 'EXT. GRID WALK - PRE-RACE', location: 'Monaco', typeTag: 'Daily', confidence: 0.88, keywords: ['A-cam', 'walk and talk', 'grid'], analyzedAt: '2026-02-15T06:00:00Z', status: 'complete' },
  'gen-cam-ferreira-02': { sourceFileId: 'gen-cam-ferreira-02', characters: ['Luca Ferreira'], scene: 'INT. APEX GARAGE - RACE DAY', location: 'Apex Garage', typeTag: 'Daily', confidence: 0.86, keywords: ['helmet on', 'cockpit', 'pre-race'], analyzedAt: '2026-02-15T06:15:00Z', status: 'complete' },
  'gen-cam-ferreira-03': { sourceFileId: 'gen-cam-ferreira-03', characters: ['Luca Ferreira', 'Frank Castellano'], scene: 'EXT. PADDOCK - POST-RACE', location: 'Paddock Club', typeTag: 'Camera Select', confidence: 0.91, keywords: ['celebration', 'podium walk', 'team'], analyzedAt: '2026-02-15T07:00:00Z', status: 'complete' },
  'gen-cam-ferreira-04': { sourceFileId: 'gen-cam-ferreira-04', characters: ['Luca Ferreira'], scene: 'EXT. CIRCUIT - LAP 52', typeTag: 'Daily', confidence: 0.84, keywords: ['onboard', 'helmet cam', 'overtake'], analyzedAt: '2026-02-15T07:30:00Z', status: 'complete' },
  'gen-cam-ferreira-05': { sourceFileId: 'gen-cam-ferreira-05', characters: ['Luca Ferreira', 'James Ashworth'], scene: 'EXT. PADDOCK - POST-RACE', location: 'Paddock Club', typeTag: 'Camera Select', confidence: 0.89, keywords: ['handshake', 'sportsmanship', 'two-shot'], analyzedAt: '2026-02-15T08:00:00Z', status: 'complete' },
  'gen-cam-ferreira-06': { sourceFileId: 'gen-cam-ferreira-06', characters: ['Luca Ferreira'], location: 'Pit Lane', typeTag: 'Daily', confidence: 0.82, keywords: ['pit stop', 'tire change', 'close-up'], analyzedAt: '2026-02-16T06:00:00Z', status: 'complete' },
  'gen-cam-ferreira-07': { sourceFileId: 'gen-cam-ferreira-07', characters: ['Luca Ferreira'], scene: 'INT. APEX GARAGE - RACE DAY', location: 'Apex Garage', typeTag: 'Camera Select', confidence: 0.93, keywords: ['visor up', 'reaction', 'hero moment'], analyzedAt: '2026-02-16T06:30:00Z', status: 'complete' },
  'gen-cam-ferreira-08': { sourceFileId: 'gen-cam-ferreira-08', characters: ['Luca Ferreira', 'Elena Richter'], scene: 'EXT. GRID WALK - PRE-RACE', location: 'Monaco', typeTag: 'Daily', confidence: 0.85, keywords: ['confrontation', 'grid', 'tension'], analyzedAt: '2026-02-16T07:00:00Z', status: 'complete' },
  'gen-cam-ferreira-09': { sourceFileId: 'gen-cam-ferreira-09', characters: ['Luca Ferreira'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Zandvoort Circuit', typeTag: 'Daily', confidence: 0.87, keywords: ['rain', 'spray', 'wet racing'], analyzedAt: '2026-02-16T07:30:00Z', status: 'complete' },
  'gen-cam-ferreira-10': { sourceFileId: 'gen-cam-ferreira-10', characters: ['Luca Ferreira'], scene: 'INT. MERCEDES MOTORHOME - DEBRIEF', typeTag: 'Camera Select', confidence: 0.90, keywords: ['interview', 'media pen', 'close-up'], analyzedAt: '2026-02-16T08:00:00Z', status: 'complete' },

  // ── Camera dailies & selects: Frank Castellano coverage ──
  'gen-cam-castellano-01': { sourceFileId: 'gen-cam-castellano-01', characters: ['Frank Castellano'], scene: 'INT. APEX GARAGE - RACE DAY', location: 'Apex Garage', typeTag: 'Daily', confidence: 0.86, keywords: ['pit wall', 'radio', 'strategy call'], analyzedAt: '2026-02-15T09:00:00Z', status: 'complete' },
  'gen-cam-castellano-02': { sourceFileId: 'gen-cam-castellano-02', characters: ['Frank Castellano', 'Luca Ferreira'], scene: 'EXT. PADDOCK - POST-RACE', location: 'Paddock Club', typeTag: 'Camera Select', confidence: 0.90, keywords: ['debrief', 'team photo', 'trophy'], analyzedAt: '2026-02-15T09:30:00Z', status: 'complete' },
  'gen-cam-castellano-03': { sourceFileId: 'gen-cam-castellano-03', characters: ['Frank Castellano'], scene: 'INT. FIA STEWARDS OFFICE - EVENING', location: 'FIA Stewards Office', typeTag: 'Daily', confidence: 0.84, keywords: ['hearing', 'argument', 'close-up'], analyzedAt: '2026-02-15T10:00:00Z', status: 'complete' },
  'gen-cam-castellano-04': { sourceFileId: 'gen-cam-castellano-04', characters: ['Frank Castellano', 'Viktor Dragan'], scene: 'EXT. GRID WALK - PRE-RACE', location: 'Monaco', typeTag: 'Daily', confidence: 0.83, keywords: ['rivalry', 'stare down', 'grid'], analyzedAt: '2026-02-15T10:30:00Z', status: 'complete' },
  'gen-cam-castellano-05': { sourceFileId: 'gen-cam-castellano-05', characters: ['Frank Castellano'], location: 'Pit Lane', typeTag: 'Camera Select', confidence: 0.88, keywords: ['pit wall', 'reaction', 'frustration'], analyzedAt: '2026-02-16T09:00:00Z', status: 'complete' },
  'gen-cam-castellano-06': { sourceFileId: 'gen-cam-castellano-06', characters: ['Frank Castellano'], scene: 'INT. MERCEDES MOTORHOME - DEBRIEF', typeTag: 'Daily', confidence: 0.81, keywords: ['press conference', 'media', 'quote'], analyzedAt: '2026-02-16T09:30:00Z', status: 'complete' },
  'gen-cam-castellano-07': { sourceFileId: 'gen-cam-castellano-07', characters: ['Frank Castellano', 'Elena Richter'], scene: 'INT. FIA STEWARDS OFFICE - EVENING', location: 'FIA Stewards Office', typeTag: 'Camera Select', confidence: 0.92, keywords: ['confrontation', 'penalty', 'heated'], analyzedAt: '2026-02-16T10:00:00Z', status: 'complete' },

  // ── Camera dailies & selects: Elena Richter coverage ──
  'gen-cam-richter-01': { sourceFileId: 'gen-cam-richter-01', characters: ['Elena Richter'], scene: 'INT. MERCEDES MOTORHOME - DEBRIEF', typeTag: 'Daily', confidence: 0.87, keywords: ['strategy', 'whiteboard', 'analysis'], analyzedAt: '2026-02-15T11:00:00Z', status: 'complete' },
  'gen-cam-richter-02': { sourceFileId: 'gen-cam-richter-02', characters: ['Elena Richter', 'James Ashworth'], scene: 'INT. APEX GARAGE - RACE DAY', location: 'Apex Garage', typeTag: 'Camera Select', confidence: 0.91, keywords: ['driver briefing', 'two-shot', 'strategy'], analyzedAt: '2026-02-15T11:30:00Z', status: 'complete' },
  'gen-cam-richter-03': { sourceFileId: 'gen-cam-richter-03', characters: ['Elena Richter'], scene: 'EXT. GRID WALK - PRE-RACE', location: 'Monaco', typeTag: 'Daily', confidence: 0.85, keywords: ['VIP', 'grid walk', 'authority'], analyzedAt: '2026-02-15T12:00:00Z', status: 'complete' },
  'gen-cam-richter-04': { sourceFileId: 'gen-cam-richter-04', characters: ['Elena Richter'], location: 'Pit Lane', typeTag: 'Camera Select', confidence: 0.89, keywords: ['pit wall', 'headset', 'radio call'], analyzedAt: '2026-02-16T11:00:00Z', status: 'complete' },
  'gen-cam-richter-05': { sourceFileId: 'gen-cam-richter-05', characters: ['Elena Richter', 'Viktor Dragan'], scene: 'EXT. PADDOCK - POST-RACE', location: 'Paddock Club', typeTag: 'Daily', confidence: 0.86, keywords: ['handshake', 'politics', 'paddock'], analyzedAt: '2026-02-16T11:30:00Z', status: 'complete' },
  'gen-cam-richter-06': { sourceFileId: 'gen-cam-richter-06', characters: ['Elena Richter'], scene: 'INT. FIA STEWARDS OFFICE - EVENING', location: 'FIA Stewards Office', typeTag: 'Daily', confidence: 0.83, keywords: ['protest', 'documents', 'formal'], analyzedAt: '2026-02-16T12:00:00Z', status: 'complete' },
  'gen-cam-richter-07': { sourceFileId: 'gen-cam-richter-07', characters: ['Elena Richter'], scene: 'INT. MERCEDES MOTORHOME - DEBRIEF', typeTag: 'Camera Select', confidence: 0.92, keywords: ['celebration', 'champagne', 'team'], analyzedAt: '2026-02-17T11:00:00Z', status: 'complete' },

  // ── Camera dailies: James Ashworth extra coverage ──
  'gen-cam-ashworth-01': { sourceFileId: 'gen-cam-ashworth-01', characters: ['James Ashworth'], scene: 'INT. APEX GARAGE - RACE DAY', location: 'Apex Garage', typeTag: 'Daily', confidence: 0.88, keywords: ['suit up', 'focus', 'veteran'], analyzedAt: '2026-02-15T13:00:00Z', status: 'complete' },
  'gen-cam-ashworth-02': { sourceFileId: 'gen-cam-ashworth-02', characters: ['James Ashworth'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Zandvoort Circuit', typeTag: 'Daily', confidence: 0.85, keywords: ['defensive driving', 'mirror', 'pressure'], analyzedAt: '2026-02-15T13:30:00Z', status: 'complete' },
  'gen-cam-ashworth-03': { sourceFileId: 'gen-cam-ashworth-03', characters: ['James Ashworth', 'Marco Vitale'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Monaco', typeTag: 'Camera Select', confidence: 0.93, keywords: ['wheel to wheel', 'battle', 'DRS'], analyzedAt: '2026-02-15T14:00:00Z', status: 'complete' },
  'gen-cam-ashworth-04': { sourceFileId: 'gen-cam-ashworth-04', characters: ['James Ashworth'], scene: 'EXT. PADDOCK - POST-RACE', location: 'Paddock Club', typeTag: 'Daily', confidence: 0.82, keywords: ['cool down', 'helmet off', 'exhausted'], analyzedAt: '2026-02-16T13:00:00Z', status: 'complete' },
  'gen-cam-ashworth-05': { sourceFileId: 'gen-cam-ashworth-05', characters: ['James Ashworth'], location: 'Pit Lane', typeTag: 'Camera Select', confidence: 0.90, keywords: ['pit entry', 'tire marks', 'speed'], analyzedAt: '2026-02-16T13:30:00Z', status: 'complete' },
  'gen-cam-ashworth-06': { sourceFileId: 'gen-cam-ashworth-06', characters: ['James Ashworth', 'Elena Richter'], scene: 'INT. MERCEDES MOTORHOME - DEBRIEF', typeTag: 'Daily', confidence: 0.87, keywords: ['debrief', 'data review', 'strategy'], analyzedAt: '2026-02-16T14:00:00Z', status: 'complete' },

  // ── Camera dailies: Viktor Dragan extra coverage ──
  'gen-cam-dragan-01': { sourceFileId: 'gen-cam-dragan-01', characters: ['Viktor Dragan'], scene: 'INT. APEX GARAGE - RACE DAY', location: 'Apex Garage', typeTag: 'Daily', confidence: 0.86, keywords: ['pit wall', 'earpiece', 'intense'], analyzedAt: '2026-02-15T15:00:00Z', status: 'complete' },
  'gen-cam-dragan-02': { sourceFileId: 'gen-cam-dragan-02', characters: ['Viktor Dragan', 'Marco Vitale'], scene: 'EXT. GRID WALK - PRE-RACE', location: 'Monaco', typeTag: 'Camera Select', confidence: 0.91, keywords: ['pep talk', 'grid', 'mentor'], analyzedAt: '2026-02-15T15:30:00Z', status: 'complete' },
  'gen-cam-dragan-03': { sourceFileId: 'gen-cam-dragan-03', characters: ['Viktor Dragan'], scene: 'INT. FIA STEWARDS OFFICE - EVENING', location: 'FIA Stewards Office', typeTag: 'Daily', confidence: 0.84, keywords: ['appeal', 'gesticulating', 'passion'], analyzedAt: '2026-02-16T15:00:00Z', status: 'complete' },
  'gen-cam-dragan-04': { sourceFileId: 'gen-cam-dragan-04', characters: ['Viktor Dragan'], location: 'Pit Lane', typeTag: 'Camera Select', confidence: 0.88, keywords: ['watching race', 'tension', 'monitor'], analyzedAt: '2026-02-16T15:30:00Z', status: 'complete' },

  // ── VFX shots: Race sequences (Ep 1-3) ──
  'gen-vfx-race-001': { sourceFileId: 'gen-vfx-race-001', characters: ['AR-24'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Monaco', typeTag: 'VFX Comp', confidence: 0.92, keywords: ['CG car', 'tunnel exit', 'comp'], analyzedAt: '2026-02-17T08:00:00Z', status: 'complete' },
  'gen-vfx-race-002': { sourceFileId: 'gen-vfx-race-002', characters: ['AR-24', 'Richter RM-15'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Monaco', typeTag: 'VFX Comp', confidence: 0.90, keywords: ['wheel to wheel', 'CG cars', 'sparks'], analyzedAt: '2026-02-17T08:30:00Z', status: 'complete' },
  'gen-vfx-race-003': { sourceFileId: 'gen-vfx-race-003', characters: ['AR-24'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Zandvoort Circuit', typeTag: 'VFX Comp', confidence: 0.88, keywords: ['rain', 'spray', 'CG weather'], analyzedAt: '2026-02-17T09:00:00Z', status: 'complete' },
  'gen-vfx-race-004': { sourceFileId: 'gen-vfx-race-004', characters: ['Richter RM-15'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Monaco', typeTag: 'VFX Comp', confidence: 0.87, keywords: ['pit exit', 'CG car', 'tire smoke'], analyzedAt: '2026-02-17T09:30:00Z', status: 'complete' },
  'gen-vfx-race-005': { sourceFileId: 'gen-vfx-race-005', characters: ['AR-24'], location: 'Pit Lane', typeTag: 'VFX Comp', confidence: 0.91, keywords: ['pit stop', 'CG crew', 'tire change'], analyzedAt: '2026-02-17T10:00:00Z', status: 'complete' },
  'gen-vfx-race-006': { sourceFileId: 'gen-vfx-race-006', characters: ['Richter RM-15'], location: 'Pit Lane', typeTag: 'VFX Comp', confidence: 0.89, keywords: ['pit stop', 'CG overlay', 'halo GFX'], analyzedAt: '2026-02-17T10:30:00Z', status: 'complete' },
  'gen-vfx-race-007': { sourceFileId: 'gen-vfx-race-007', characters: ['AR-24'], scene: 'EXT. GRID WALK - PRE-RACE', location: 'Zandvoort Circuit', typeTag: 'VFX Comp', confidence: 0.86, keywords: ['grid lineup', 'CG crowd', 'atmosphere'], analyzedAt: '2026-02-17T11:00:00Z', status: 'complete' },
  'gen-vfx-crash-001': { sourceFileId: 'gen-vfx-crash-001', characters: ['AR-24'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Monaco', typeTag: 'VFX Comp', confidence: 0.94, keywords: ['crash', 'debris', 'CG destruction', 'safety car'], analyzedAt: '2026-02-18T08:00:00Z', status: 'complete' },
  'gen-vfx-crash-002': { sourceFileId: 'gen-vfx-crash-002', characters: ['Richter RM-15'], scene: 'EXT. CIRCUIT - LAP 52', location: 'Zandvoort Circuit', typeTag: 'VFX Comp', confidence: 0.92, keywords: ['spin', 'gravel', 'CG particles'], analyzedAt: '2026-02-18T08:30:00Z', status: 'complete' },
  'gen-vfx-crowd-001': { sourceFileId: 'gen-vfx-crowd-001', characters: [], scene: 'EXT. GRID WALK - PRE-RACE', location: 'Monaco', typeTag: 'VFX Comp', confidence: 0.85, keywords: ['crowd extension', 'grandstand', 'CG fill'], analyzedAt: '2026-02-18T09:00:00Z', status: 'complete' },
  'gen-vfx-crowd-002': { sourceFileId: 'gen-vfx-crowd-002', characters: [], scene: 'EXT. CIRCUIT - LAP 52', location: 'Zandvoort Circuit', typeTag: 'VFX Comp', confidence: 0.83, keywords: ['orange army', 'crowd extension', 'CG'], analyzedAt: '2026-02-18T09:30:00Z', status: 'complete' },

  // ── Art: Character & car designs ──
  'gen-art-ferreira-helmet': { sourceFileId: 'gen-art-ferreira-helmet', characters: ['Luca Ferreira'], typeTag: 'Concept Art', confidence: 0.91, keywords: ['helmet', 'design', 'livery'], analyzedAt: '2026-02-13T08:00:00Z', status: 'complete' },
  'gen-art-ferreira-suit': { sourceFileId: 'gen-art-ferreira-suit', characters: ['Luca Ferreira'], typeTag: 'Costume Design', confidence: 0.89, keywords: ['race suit', 'sponsor layout', 'design'], analyzedAt: '2026-02-13T08:30:00Z', status: 'complete' },
  'gen-art-ashworth-helmet': { sourceFileId: 'gen-art-ashworth-helmet', characters: ['James Ashworth'], typeTag: 'Concept Art', confidence: 0.90, keywords: ['helmet', 'design', 'retro'], analyzedAt: '2026-02-13T09:00:00Z', status: 'complete' },
  'gen-art-richter-office': { sourceFileId: 'gen-art-richter-office', characters: ['Elena Richter'], location: 'Paddock Club', typeTag: 'Set Design', confidence: 0.86, keywords: ['motorhome interior', 'modern', 'glass'], analyzedAt: '2026-02-13T09:30:00Z', status: 'complete' },
  'gen-art-castellano-portrait': { sourceFileId: 'gen-art-castellano-portrait', characters: ['Frank Castellano'], typeTag: 'Character', confidence: 0.88, keywords: ['portrait', 'reference', 'wardrobe'], analyzedAt: '2026-02-13T10:00:00Z', status: 'complete' },
  'gen-art-ar24-livery-v2': { sourceFileId: 'gen-art-ar24-livery-v2', characters: ['AR-24'], typeTag: 'Concept Art', confidence: 0.93, keywords: ['livery', 'iteration', 'sponsor'], analyzedAt: '2026-02-13T10:30:00Z', status: 'complete' },
  'gen-art-ar24-livery-v3': { sourceFileId: 'gen-art-ar24-livery-v3', characters: ['AR-24'], typeTag: 'Concept Art', confidence: 0.94, keywords: ['livery', 'final', 'approved'], analyzedAt: '2026-02-14T08:00:00Z', status: 'complete' },
  'gen-art-rm15-livery': { sourceFileId: 'gen-art-rm15-livery', characters: ['Richter RM-15'], typeTag: 'Concept Art', confidence: 0.91, keywords: ['livery', 'silver', 'design'], analyzedAt: '2026-02-13T11:00:00Z', status: 'complete' },
  'gen-art-rm15-detail': { sourceFileId: 'gen-art-rm15-detail', characters: ['Richter RM-15'], typeTag: 'Concept Art', confidence: 0.88, keywords: ['sidepod', 'detail', 'aero'], analyzedAt: '2026-02-13T11:30:00Z', status: 'complete' },
  'gen-art-monaco-env': { sourceFileId: 'gen-art-monaco-env', characters: [], location: 'Monaco', typeTag: 'Environment', confidence: 0.87, keywords: ['harbor', 'circuit', 'establishing'], analyzedAt: '2026-02-13T12:00:00Z', status: 'complete' },
  'gen-art-zandvoort-env': { sourceFileId: 'gen-art-zandvoort-env', characters: [], location: 'Zandvoort Circuit', typeTag: 'Environment', confidence: 0.85, keywords: ['dunes', 'banking', 'circuit'], analyzedAt: '2026-02-13T12:30:00Z', status: 'complete' },
  'gen-art-pitlane-env': { sourceFileId: 'gen-art-pitlane-env', characters: [], location: 'Pit Lane', typeTag: 'Environment', confidence: 0.84, keywords: ['pit lane', 'overhead', 'layout'], analyzedAt: '2026-02-13T13:00:00Z', status: 'complete' },
  'gen-art-fia-office-set': { sourceFileId: 'gen-art-fia-office-set', characters: [], location: 'FIA Stewards Office', typeTag: 'Set Design', confidence: 0.86, keywords: ['interior', 'formal', 'hearing room'], analyzedAt: '2026-02-13T13:30:00Z', status: 'complete' },
  'gen-art-paddock-set': { sourceFileId: 'gen-art-paddock-set', characters: [], location: 'Paddock Club', typeTag: 'Set Design', confidence: 0.83, keywords: ['hospitality', 'VIP', 'lounge'], analyzedAt: '2026-02-13T14:00:00Z', status: 'complete' },

  // ── Audio: Per-character ADR and per-location atmosphere ──
  'gen-audio-ferreira-adr-01': { sourceFileId: 'gen-audio-ferreira-adr-01', characters: ['Luca Ferreira'], typeTag: 'ADR', confidence: 0.88, keywords: ['adr', 'dialogue', 'radio call'], analyzedAt: '2026-02-14T08:00:00Z', status: 'complete' },
  'gen-audio-ferreira-adr-02': { sourceFileId: 'gen-audio-ferreira-adr-02', characters: ['Luca Ferreira'], typeTag: 'ADR', confidence: 0.86, keywords: ['adr', 'celebration', 'team radio'], analyzedAt: '2026-02-14T08:30:00Z', status: 'complete' },
  'gen-audio-ashworth-adr': { sourceFileId: 'gen-audio-ashworth-adr', characters: ['James Ashworth'], typeTag: 'ADR', confidence: 0.87, keywords: ['adr', 'dialogue', 'interview'], analyzedAt: '2026-02-14T09:00:00Z', status: 'complete' },
  'gen-audio-richter-adr': { sourceFileId: 'gen-audio-richter-adr', characters: ['Elena Richter'], typeTag: 'ADR', confidence: 0.85, keywords: ['adr', 'dialogue', 'radio call'], analyzedAt: '2026-02-14T09:30:00Z', status: 'complete' },
  'gen-audio-castellano-adr': { sourceFileId: 'gen-audio-castellano-adr', characters: ['Frank Castellano'], typeTag: 'ADR', confidence: 0.84, keywords: ['adr', 'dialogue', 'press conference'], analyzedAt: '2026-02-14T10:00:00Z', status: 'complete' },
  'gen-audio-dragan-adr': { sourceFileId: 'gen-audio-dragan-adr', characters: ['Viktor Dragan'], typeTag: 'ADR', confidence: 0.86, keywords: ['adr', 'dialogue', 'team radio'], analyzedAt: '2026-02-14T10:30:00Z', status: 'complete' },
  'gen-audio-monaco-atmos': { sourceFileId: 'gen-audio-monaco-atmos', characters: [], location: 'Monaco', typeTag: 'Ambient', confidence: 0.91, keywords: ['harbor', 'crowd', 'atmosphere', 'glamour'], analyzedAt: '2026-02-14T11:00:00Z', status: 'complete' },
  'gen-audio-zandvoort-atmos': { sourceFileId: 'gen-audio-zandvoort-atmos', characters: [], location: 'Zandvoort Circuit', typeTag: 'Ambient', confidence: 0.89, keywords: ['crowd', 'orange smoke', 'chanting'], analyzedAt: '2026-02-14T11:30:00Z', status: 'complete' },
  'gen-audio-garage-atmos': { sourceFileId: 'gen-audio-garage-atmos', characters: [], location: 'Apex Garage', typeTag: 'Ambient', confidence: 0.88, keywords: ['air guns', 'radio chatter', 'mechanical'], analyzedAt: '2026-02-14T12:00:00Z', status: 'complete' },
  'gen-audio-engine-ar24': { sourceFileId: 'gen-audio-engine-ar24', characters: ['AR-24'], typeTag: 'SFX', confidence: 0.95, keywords: ['engine', 'rev', 'acceleration', 'downshift'], analyzedAt: '2026-02-14T12:30:00Z', status: 'complete' },
  'gen-audio-engine-rm15': { sourceFileId: 'gen-audio-engine-rm15', characters: ['Richter RM-15'], typeTag: 'SFX', confidence: 0.94, keywords: ['engine', 'rev', 'turbo', 'ERS'], analyzedAt: '2026-02-14T13:00:00Z', status: 'complete' },

  // ── Editorial: More episode cuts featuring underrepresented characters ──
  'gen-edit-ep02-rough': { sourceFileId: 'gen-edit-ep02-rough', characters: ['Luca Ferreira', 'Frank Castellano', 'Elena Richter'], scene: 'EXT. CIRCUIT - LAP 52', typeTag: 'Rough Cut', confidence: 0.88, keywords: ['EP02', 'rough cut', 'race episode'], analyzedAt: '2026-02-15T14:00:00Z', status: 'complete' },
  'gen-edit-ep03-assembly': { sourceFileId: 'gen-edit-ep03-assembly', characters: ['James Ashworth', 'Elena Richter', 'Viktor Dragan'], scene: 'INT. MERCEDES MOTORHOME - DEBRIEF', typeTag: 'Assembly', confidence: 0.84, keywords: ['EP03', 'assembly', 'politics episode'], analyzedAt: '2026-02-16T14:00:00Z', status: 'complete' },
  'gen-edit-ep04-selects': { sourceFileId: 'gen-edit-ep04-selects', characters: ['Marco Vitale', 'Luca Ferreira', 'Frank Castellano'], scene: 'EXT. GRID WALK - PRE-RACE', typeTag: 'Assembly', confidence: 0.82, keywords: ['EP04', 'selects reel', 'Monaco GP'], analyzedAt: '2026-02-17T14:00:00Z', status: 'complete' },

  // ── Camera B-roll: Circuit & location coverage ──
  'gen-cam-broll-monaco-01': { sourceFileId: 'gen-cam-broll-monaco-01', characters: [], location: 'Monaco', typeTag: 'B-Roll', confidence: 0.80, keywords: ['harbor', 'establishing', 'golden hour'], analyzedAt: '2026-02-15T16:00:00Z', status: 'complete' },
  'gen-cam-broll-monaco-02': { sourceFileId: 'gen-cam-broll-monaco-02', characters: [], location: 'Monaco', typeTag: 'B-Roll', confidence: 0.78, keywords: ['tunnel', 'cars passing', 'atmos'], analyzedAt: '2026-02-15T16:30:00Z', status: 'complete' },
  'gen-cam-broll-zandvoort': { sourceFileId: 'gen-cam-broll-zandvoort', characters: [], location: 'Zandvoort Circuit', typeTag: 'B-Roll', confidence: 0.79, keywords: ['dunes', 'beach', 'establishing'], analyzedAt: '2026-02-15T17:00:00Z', status: 'complete' },
  'gen-cam-broll-pitlane-01': { sourceFileId: 'gen-cam-broll-pitlane-01', characters: [], location: 'Pit Lane', typeTag: 'B-Roll', confidence: 0.81, keywords: ['pit crew', 'equipment', 'prep'], analyzedAt: '2026-02-15T17:30:00Z', status: 'complete' },
  'gen-cam-broll-pitlane-02': { sourceFileId: 'gen-cam-broll-pitlane-02', characters: [], location: 'Pit Lane', typeTag: 'B-Roll', confidence: 0.80, keywords: ['night', 'lights', 'atmosphere'], analyzedAt: '2026-02-16T16:00:00Z', status: 'complete' },
  'gen-cam-broll-paddock': { sourceFileId: 'gen-cam-broll-paddock', characters: [], location: 'Paddock Club', typeTag: 'B-Roll', confidence: 0.77, keywords: ['hospitality', 'motorhomes', 'wide'], analyzedAt: '2026-02-16T16:30:00Z', status: 'complete' },
  'gen-cam-broll-garage': { sourceFileId: 'gen-cam-broll-garage', characters: [], location: 'Apex Garage', typeTag: 'B-Roll', confidence: 0.82, keywords: ['tools', 'car parts', 'detail shots'], analyzedAt: '2026-02-16T17:00:00Z', status: 'complete' },

  // ── VFX: Matte paintings & environment extensions ──
  'gen-vfx-matte-monaco': { sourceFileId: 'gen-vfx-matte-monaco', characters: [], location: 'Monaco', typeTag: 'Matte Painting', confidence: 0.87, keywords: ['harbor skyline', 'sunset', 'establishing'], analyzedAt: '2026-02-18T10:00:00Z', status: 'complete' },
  'gen-vfx-matte-zandvoort': { sourceFileId: 'gen-vfx-matte-zandvoort', characters: [], location: 'Zandvoort Circuit', typeTag: 'Matte Painting', confidence: 0.85, keywords: ['coast', 'dunes', 'sky extension'], analyzedAt: '2026-02-18T10:30:00Z', status: 'complete' },
  'gen-vfx-matte-pitlane-night': { sourceFileId: 'gen-vfx-matte-pitlane-night', characters: [], location: 'Pit Lane', typeTag: 'Matte Painting', confidence: 0.84, keywords: ['night', 'floodlights', 'atmosphere'], analyzedAt: '2026-02-18T11:00:00Z', status: 'complete' },
}

/** Look up AI tags for a workspace file by its file node ID */
export function getAITagsForFile(fileId: string, fileName?: string): AITagResult | undefined {
  const existing = MOCK_AI_TAGS[fileId]
  if (existing) return existing

  // Generate fallback AI tags for dynamically created camera files
  if (fileName && /\.(mxf|mov|r3d|braw)$/i.test(fileName)) {
    return {
      sourceFileId: fileId,
      characters: [],
      location: 'Circuit',
      typeTag: 'Camera Daily',
      confidence: 0.88,
      keywords: ['dailies', 'camera original'],
      analyzedAt: new Date().toISOString(),
      status: 'complete',
    }
  }
  return undefined
}

/** Find workspace file IDs whose AI tags match a given dimension value */
export function getFileIdsByCharacter(character: string): string[] {
  return Object.keys(MOCK_AI_TAGS).filter(id =>
    MOCK_AI_TAGS[id].characters.some(c => c === character)
  )
}

export function getFileIdsByLocation(location: string): string[] {
  return Object.keys(MOCK_AI_TAGS).filter(id =>
    MOCK_AI_TAGS[id].location === location
  )
}

export function getFileIdsByScene(scene: string): string[] {
  return Object.keys(MOCK_AI_TAGS).filter(id =>
    MOCK_AI_TAGS[id].scene === scene
  )
}

/** Convert an AITagResult to the AIMeta shape stored on Asset. */
export function toAIMeta(tags: AITagResult): AIMeta {
  return {
    characters: tags.characters.length > 0 ? tags.characters : undefined,
    scene: tags.scene,
    location: tags.location,
    productionShot: tags.productionShot,
    cgShot: tags.cgShot,
    cgSequence: tags.cgSequence,
    editSequence: tags.editSequence,
    confidence: tags.confidence,
    keywords: tags.keywords,
  }
}
