import type { DomainConfig, DomainId } from '@/components/department/types'

export const domainConfigs: Record<DomainId, DomainConfig> = {
  'art-design': {
    id: 'art-design',
    name: 'Art & Design',
    shortName: 'Art & Design',
    description: 'Concept art, storyboards, and design assets',
    smartCollectionTypes: ['character', 'location', 'scene'],
    userCollectionType: 'art-type',
    color: 'bg-purple-500',
    kind: 'production',
  },
  vfx: {
    id: 'vfx',
    name: 'VFX',
    shortName: 'VFX',
    description: 'Visual effects, compositing, and 3D assets',
    smartCollectionTypes: ['character', 'location', 'scene'],
    userCollectionType: 'art-type',
    color: 'bg-blue-500',
    kind: 'production',
  },
  camera: {
    id: 'camera',
    name: 'Camera',
    shortName: 'Camera',
    description: 'Dailies, camera tests, and production footage',
    smartCollectionTypes: ['scene'],
    userCollectionType: 'art-type',
    color: 'bg-green-500',
    kind: 'production',
  },
  editorial: {
    id: 'editorial',
    name: 'Editorial',
    shortName: 'Editorial',
    description: 'Cuts, color passes, and delivery masters',
    smartCollectionTypes: ['scene'],
    userCollectionType: 'art-type',
    color: 'bg-yellow-500',
    kind: 'production',
  },
  'audio-sound': {
    id: 'audio-sound',
    name: 'Audio & Sound',
    shortName: 'Audio',
    description: 'Production sound, SFX, foley, and music',
    smartCollectionTypes: ['scene'],
    userCollectionType: 'art-type',
    color: 'bg-red-500',
    kind: 'production',
  },
  marketing: {
    id: 'marketing',
    name: 'Marketing',
    shortName: 'Marketing',
    description: 'Campaign assets, key art, and promotional content',
    smartCollectionTypes: [],
    userCollectionType: 'art-type',
    color: 'bg-orange-500',
    kind: 'distribution',
  },
  legal: {
    id: 'legal',
    name: 'Legal',
    shortName: 'Legal',
    description: 'Compliance reviews and clearance assets',
    smartCollectionTypes: [],
    userCollectionType: 'art-type',
    color: 'bg-gray-500',
    kind: 'distribution',
  },
  globalization: {
    id: 'globalization',
    name: 'Globalization',
    shortName: 'Globalization',
    description: 'Localization, dubbing, and subtitle assets',
    smartCollectionTypes: [],
    userCollectionType: 'art-type',
    color: 'bg-teal-500',
    kind: 'distribution',
  },
}