'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, PanelRight } from 'lucide-react'
import { cn } from '@/lib/utils'
import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import {
  Stack,
  Text,
  PageHeader,
  Button,
  CardGrid,
  AssetCard,
  CollectionCard,
  SelectionBar,
  EmptyState,
  SmartCollectionSidePanel,
  AssetDetailPanel,
  HawkinsSearch,
  SortDropdown,
  AppearanceDropdown,
  CompactBar,
} from '@/components/ui'
import type { CollectionCardType } from '@/components/ui/collection-card'
import type { SortCriterion } from '@/components/ui/sort-dropdown'
import { AppLayout } from '@/components/layouts'
import { useAssetSelection, useViewPreferences, useCompactBar, useResourceSelection, useUserCollections, useSmartCollections, usePersona } from '@/hooks'
import { matchesFilter } from '@/hooks/useSmartCollections'
import { useBreadcrumbExtras } from '@/components/ui/project-breadcrumb'
import type { AssetFilter } from '@/lib/data'
import { assetToSelectionEntity, collectionToSelectionEntity } from '@/lib/selection-actions'

interface SmartCollectionDetailViewProps {
  collectionId: string
}

export function SmartCollectionDetailView({ collectionId }: SmartCollectionDetailViewProps) {
  const pathname = usePathname()
  const router = useRouter()
  const menuHref = `/nextgen/menu?return=${encodeURIComponent(pathname)}`

  const { getCollection, getChildren, getRelatedCollections, updateCollection, deleteCollection, allAssets, scopedAssets, assetsLoading } = useSmartCollections()
  const { activePersona } = usePersona()
  const { createCollection: createUserCollection } = useUserCollections()
  const {
    selectedIds: selectedAssetIds,
    primaryId: primaryAssetId,
    handleSelectionClick: handleAssetClick,
    clearSelection: clearAssetSelection,
  } = useAssetSelection()
  const {
    selectedIds: selectedCollectionIds,
    primaryId: selectedCollectionId,
    handleSelectionClick: handleCollectionSelectionClick,
    clearSelection: clearCollectionSelection,
  } = useResourceSelection<{ id: string; name: string }>()
  const { layout, setLayout, cardSize, setCardSize, sidePanelOpen, setSidePanelOpen } = useViewPreferences()
  const { scrollRef, headerRef, showCompactBar } = useCompactBar()
  const { setBreadcrumbExtras, clearBreadcrumbExtras } = useBreadcrumbExtras()

  const [searchQuery, setSearchQuery] = useState('')
  const [sortCriteria, setSortCriteria] = useState<SortCriterion[]>([
    { field: 'name', direction: 'asc' },
  ])

  const collection = getCollection(collectionId)

  // For child collections, find the parent
  const parentCollection = useMemo(() => {
    if (!collection?.parentId) return undefined
    return getCollection(collection.parentId)
  }, [collection, getCollection])

  const isAutoGeneratedChild = !!collection?.parentId

  // Compute ontology relationships for child collections
  const relationships = useMemo(() => {
    if (!isAutoGeneratedChild) return undefined
    return getRelatedCollections(collectionId)
  }, [isAutoGeneratedChild, collectionId, getRelatedCollections])

  // Sync breadcrumb with collection name
  useEffect(() => {
    if (!collection) return
    const extras: { label: string; href?: string }[] = []
    if (parentCollection) {
      extras.push({ label: parentCollection.name, href: `/nextgen/smart-collections/${parentCollection.id}` })
    }
    extras.push({ label: collection.name })
    setBreadcrumbExtras(extras)
    return () => clearBreadcrumbExtras()
  }, [collection, parentCollection, setBreadcrumbExtras, clearBreadcrumbExtras])

  // Filter assets based on collection's filter rules (scoped by persona access)
  const filteredAssets = useMemo(() => {
    if (!collection) return []
    return scopedAssets.filter(asset => matchesFilter(asset, collection.filter))
  }, [scopedAssets, collection])

  // Parent collections with groupBy show child collection cards
  const childCollections = useMemo(() => {
    if (!collection?.groupBy) return []
    return getChildren(collection.id)
  }, [collection, getChildren])

  const isParentWithChildren = childCollections.length > 0

  // For each child, compute matching assets (for count + thumbnails + avatar)
  const childData = useMemo(() => {
    if (!isParentWithChildren) return []
    return childCollections.map((child, i) => {
      const assets = scopedAssets.filter(a => matchesFilter(a, child.filter))
      return {
        collection: child,
        assetCount: assets.length,
        mainImage: assets[0]?.thumbnail,
        thumbnailImages: assets.slice(1, 3).map(a => a.thumbnail).filter(Boolean) as string[],
        avatarSrc: `https://i.pravatar.cc/150?img=${(i * 7 + 3) % 70}`,
      }
    })
  }, [childCollections, isParentWithChildren, scopedAssets])

  // Map SmartCollectionIcon to CollectionCardType
  const cardType: CollectionCardType = collection?.icon === 'character' ? 'character'
    : collection?.icon === 'location' ? 'location'
    : collection?.icon === 'scene' ? 'scene'
    : collection?.icon === 'palette' ? 'art-type'
    : collection?.icon === 'shot' ? 'scene'
    : collection?.icon === 'sequence' ? 'scene'
    : 'character'

  const handleDeleteCollection = () => {
    if (collection && deleteCollection(collection.id)) {
      router.push('/nextgen')
    }
  }

  const handleUpdateCollection = (updates: { name?: string; filter?: AssetFilter }) => {
    if (collection) {
      updateCollection(collection.id, updates)
    }
  }

  const handleMenuClick = () => {}

  const getColumns = () => {
    switch (cardSize) {
      case 'sm': return 6
      case 'lg': return 3
      default: return 4
    }
  }

  const selectedAssets = useMemo(() => {
    return filteredAssets.filter((asset) => selectedAssetIds.has(asset.id))
  }, [filteredAssets, selectedAssetIds])
  const selectedAssetEntities = useMemo(() => selectedAssets.map((asset) => assetToSelectionEntity(asset)), [selectedAssets])
  const selectedCollectionEntities = useMemo(() => {
    return childData
      .filter((child) => selectedCollectionIds.has(child.collection.id))
      .map((child) => collectionToSelectionEntity(child.collection, 'smart-collection'))
  }, [childData, selectedCollectionIds])
  const activeSelectionEntities = isParentWithChildren ? selectedCollectionEntities : selectedAssetEntities
  const primaryAsset = useMemo(() => {
    if (!primaryAssetId) return null
    return filteredAssets.find(a => a.id === primaryAssetId) ?? null
  }, [primaryAssetId, filteredAssets])
  const selectedChildCollection = useMemo(() => {
    if (!selectedCollectionId) return null
    return childData.find(c => c.collection.id === selectedCollectionId)?.collection ?? null
  }, [selectedCollectionId, childData])
  const selectedChildRelationships = useMemo(() => {
    if (!selectedCollectionId) return undefined
    return getRelatedCollections(selectedCollectionId)
  }, [selectedCollectionId, getRelatedCollections])

  const handleCreateCollection = (name: string) => {
    createUserCollection(name, selectedAssets.map(a => a.id))
    clearAssetSelection()
  }

  const loading = assetsLoading

  const sortFields = [
    { value: 'name', label: 'Name' },
    { value: 'date-added', label: 'Date Added' },
    { value: 'date-modified', label: 'Date Modified' },
    { value: 'size', label: 'Size' },
    { value: 'kind', label: 'Kind' },
  ]

  // Contextual filter chips based on collection type
  const filterOptions = useMemo(() => {
    if (!collection) return []
    switch (collection.icon) {
      case 'character':
        return [
          { id: 'episode', label: 'Episode' },
          { id: 'role', label: 'Role' },
          { id: 'status', label: 'Status' },
        ]
      case 'scene':
        return [
          { id: 'episode', label: 'Episode' },
          { id: 'location', label: 'Location' },
          { id: 'time-of-day', label: 'Time of Day' },
        ]
      case 'location':
        return [
          { id: 'episode', label: 'Episode' },
          { id: 'scene', label: 'Scene' },
        ]
      default:
        return [
          { id: 'type', label: 'Type' },
          { id: 'modified', label: 'Modified' },
        ]
    }
  }, [collection])

  const pageTitle = collection?.name || 'Loading...'
  const itemCount = isParentWithChildren
    ? childCollections.length
    : filteredAssets.length
  const countLabel = isParentWithChildren ? 'collection' : 'asset'
  const backHref = parentCollection
    ? `/nextgen/smart-collections/${parentCollection.id}`
    : undefined

  // Collection not found
  if (!collection && !loading) {
    return (
      <AppLayout>
        <div className="h-full flex flex-col">
          <div className="flex-1 min-h-0 overflow-auto">
            <div className="p-6">
              <div className="max-w-7xl mx-auto">
                <Stack spacing="lg">
                  <div className="md:hidden">
                    <Button asChild variant="icon" size="icon" aria-label="Menu">
                      <Link href={menuHref}>
                        <ArrowLeft className="w-4 h-4" />
                        <span className="sr-only">Menu</span>
                      </Link>
                    </Button>
                  </div>
                  <EmptyState
                    title="Smart Collection not found"
                    message="This smart collection may have been deleted or doesn't exist."
                  >
                    <Button
                      variant="secondary"
                      onClick={() => router.push('/nextgen')}
                      className="mt-4"
                    >
                      Back to Home
                    </Button>
                  </EmptyState>
                </Stack>
              </div>
            </div>
          </div>
        </div>
      </AppLayout>
    )
  }

  return (
    <AppLayout>
      <div className="h-full flex">
        {/* Main content area */}
        <div className="flex-1 min-w-0 flex flex-col">
          <div ref={scrollRef} className="flex-1 min-h-0 overflow-auto">
            <CompactBar
              visible={showCompactBar}
              title={pageTitle}
              count={itemCount}
              countLabel={countLabel}
              searchQuery={searchQuery}
              onSearchChange={setSearchQuery}
              filterOptions={filterOptions}
              sortFields={sortFields}
              sortCriteria={sortCriteria}
              onSortChange={setSortCriteria}
              layout={layout}
              onLayoutChange={setLayout}
              cardSize={cardSize}
              onCardSizeChange={setCardSize}
              showLayoutOptions={false}
            />

            <div className="p-6">
              <div className="max-w-7xl mx-auto">
                <Stack spacing="lg">
                  {/* Mobile menu button */}
                  <div className="flex items-center justify-between w-full md:hidden">
                    <Button asChild variant="icon" size="icon" aria-label="Menu">
                      <Link href={menuHref}>
                        <ArrowLeft className="w-4 h-4" />
                        <span className="sr-only">Menu</span>
                      </Link>
                    </Button>
                    <div className="flex items-center gap-2">
                      <HawkinsSearch
                        value={searchQuery}
                        onValueChange={setSearchQuery}
                        filters={filterOptions}
                      />
                      <SortDropdown
                        fields={sortFields}
                        value={sortCriteria}
                        onChange={setSortCriteria}
                        iconOnly
                      />
                      <AppearanceDropdown
                        iconOnly
                        layout={layout}
                        onLayoutChange={setLayout}
                        cardSize={cardSize}
                        onCardSizeChange={setCardSize}
                        showLayoutOptions={false}
                      />
                                            <Button
                          variant="icon"
                          size="icon"
                          onClick={() => setSidePanelOpen(!sidePanelOpen)}
                          aria-label={sidePanelOpen ? 'Close panel' : 'Open panel'}
                          className={cn(sidePanelOpen && 'bg-surface-3')}
                        >
                          <PanelRight className="w-4 h-4" />
                        </Button>
                    </div>
                  </div>

                  {/* Header */}
                  <div ref={headerRef} className="flex flex-col gap-3">
                    <div className="flex items-center justify-between gap-4">
                      <PageHeader title={pageTitle} backHref={backHref} />
                      <div className="hidden md:flex items-center gap-2">
                        <SortDropdown
                          fields={sortFields}
                          value={sortCriteria}
                          onChange={setSortCriteria}
                          iconOnly={sidePanelOpen}
                        />
                        <AppearanceDropdown
                          layout={layout}
                          onLayoutChange={setLayout}
                          cardSize={cardSize}
                          onCardSizeChange={setCardSize}
                          showLayoutOptions={false}
                          iconOnly={sidePanelOpen}
                        />
                        <Button
                          variant="icon"
                          size="icon"
                          onClick={() => setSidePanelOpen(!sidePanelOpen)}
                          aria-label={sidePanelOpen ? 'Close panel' : 'Open panel'}
                          className={cn(sidePanelOpen && 'bg-surface-3')}
                        >
                          <PanelRight className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                    <div className="hidden md:block">
                      <HawkinsSearch
                        value={searchQuery}
                        onValueChange={setSearchQuery}
                        filters={filterOptions}
                      />
                    </div>
                  </div>


                  {/* Content */}
                  <div className="min-h-[400px]">
                    {loading ? (
                      <CardGrid columns={getColumns()} gap="4">
                        {[...Array(6)].map((_, i) => (
                          <CollectionCard
                            key={i}
                            title=""
                            assetCount={0}
                            state="Loading"
                            numberOfAssets="None"
                            size={cardSize}
                          />
                        ))}
                      </CardGrid>
                    ) : isParentWithChildren ? (
                      <CardGrid columns={getColumns()} gap="4">
                        {childData.map((child) => (
                          <CollectionCard
                            key={child.collection.id}
                            title={child.collection.name}
                            assetCount={child.assetCount}
                            type={cardType}
                            mainImage={child.mainImage}
                            thumbnailImages={child.thumbnailImages}
                            avatarSrc={child.avatarSrc}
                            avatarName={child.collection.name}
                            size={cardSize}
                            numberOfAssets={
                              child.assetCount === 0 ? 'None'
                              : child.assetCount === 1 ? 'One'
                              : child.assetCount === 2 ? 'Two'
                              : 'Many'
                            }
                            isSelected={selectedCollectionId === child.collection.id}
                            onClick={(event) => handleCollectionSelectionClick(child.collection, event, childData.map((entry) => entry.collection))}
                            onDoubleClick={() => router.push(`/nextgen/smart-collections/${child.collection.id}`)}
                          />
                        ))}
                      </CardGrid>
                    ) : filteredAssets.length > 0 ? (
                      <CardGrid columns={getColumns()} gap="4">
                        {filteredAssets.map((asset) => (
                          <AssetCard
                            key={asset.id}
                            asset={asset}
                            selected={selectedAssetIds.has(asset.id)}
                            primary={primaryAssetId === asset.id}
                            onClick={(a, e) => handleAssetClick(a, e, filteredAssets)}
                            onMenuClick={handleMenuClick}
                            showDepartment
                          />
                        ))}
                      </CardGrid>
                    ) : (
                      <EmptyState
                        title="No matching assets"
                        message="No assets match the current filter rules. Try adjusting the filters."
                      />
                    )}
                  </div>
                </Stack>
              </div>
            </div>
          </div>

          <SelectionBar
            selectedEntities={activeSelectionEntities}
            onClear={isParentWithChildren ? clearCollectionSelection : clearAssetSelection}
          />
        </div>

        {/* Side panel — priority: selected asset > selected child collection > current collection */}
        <AssetDetailPanel
          asset={primaryAsset!}
          open={sidePanelOpen && !!primaryAsset}
          onClose={() => { clearAssetSelection(); setSidePanelOpen(false) }}
          activeCollectionId={collectionId}
        />
        {selectedChildCollection && (
          <SmartCollectionSidePanel
            collection={selectedChildCollection}
            open={sidePanelOpen && !primaryAsset && !!selectedChildCollection}
            onClose={() => { clearCollectionSelection(); setSidePanelOpen(false) }}
            onUpdate={handleUpdateCollection}
            matchingCount={childData.find(c => c.collection.id === selectedCollectionId)?.assetCount}
            relationships={selectedChildRelationships}
          />
        )}
        {collection && (
          <SmartCollectionSidePanel
            collection={collection}
            open={sidePanelOpen && !primaryAsset && !selectedChildCollection}
            onClose={() => setSidePanelOpen(false)}
            onUpdate={handleUpdateCollection}
            onDelete={isAutoGeneratedChild ? undefined : handleDeleteCollection}
            matchingCount={filteredAssets.length}
            relationships={relationships}
          />
        )}
      </div>
    </AppLayout>
  )
}
